// DO NOT EDIT — generated from platform/ontology/shapes/book.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use super::sdk_prelude::*;

/// A book. Books are BOTH creative works (the intellectual work — its
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct Book {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub aisle: Option<String>,
    pub availability: Option<String>,
    pub awards_won: Option<Vec<String>>,
    pub barcode: Option<String>,
    pub calories: Option<f64>,
    pub categories: Option<Vec<String>>,
    pub category: Option<String>,
    pub characters: Option<Vec<String>>,
    pub copyright_year: Option<i64>,
    pub coverage: Option<String>,
    pub currency: Option<String>,
    pub customization_groups: Option<serde_json::Value>,
    pub date_created: Option<String>,
    pub department: Option<String>,
    pub description: Option<String>,
    pub format: Option<String>,
    pub genres: Option<Vec<String>>,
    pub images: Option<serde_json::Value>,
    pub isbn: Option<String>,
    pub isbn13: Option<String>,
    pub language: Option<String>,
    pub license: Option<String>,
    pub nova_group: Option<i64>,
    pub nutrition_score: Option<String>,
    pub original_price: Option<String>,
    pub original_price_amount: Option<f64>,
    pub original_title: Option<String>,
    pub pages: Option<i64>,
    pub places: Option<Vec<String>>,
    pub price: Option<String>,
    pub price_amount: Option<f64>,
    pub quantity: Option<i64>,
    pub series: Option<String>,
    pub serving_size: Option<String>,
    pub sku: Option<String>,
    pub sold_by_weight: Option<bool>,
    pub tags: Option<Vec<String>>,
    pub weight: Option<String>,
    pub weight_unit: Option<String>,
    pub weight_value: Option<f64>,
}

pub static BOOK: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "book".into(),
    plural: Some("books".into()),
    description: Some("A book. Books are BOTH creative works (the intellectual work — its".into()),
    fields: vec![
        FieldDef::optional("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("aisle", FieldType::String),
        FieldDef::optional("availability", FieldType::String),
        FieldDef::optional("awardsWon", FieldType::StringList),
        FieldDef::optional("barcode", FieldType::String),
        FieldDef::optional("calories", FieldType::Number),
        FieldDef::optional("categories", FieldType::StringList),
        FieldDef::optional("category", FieldType::String),
        FieldDef::optional("characters", FieldType::StringList),
        FieldDef::optional("copyrightYear", FieldType::Integer),
        FieldDef::optional("coverage", FieldType::String),
        FieldDef::optional("currency", FieldType::String),
        FieldDef::optional("customizationGroups", FieldType::Json),
        FieldDef::optional("dateCreated", FieldType::Date),
        FieldDef::optional("department", FieldType::String),
        FieldDef::optional("description", FieldType::String),
        FieldDef::optional("format", FieldType::String),
        FieldDef::optional("genres", FieldType::StringList),
        FieldDef::optional("images", FieldType::Json),
        FieldDef::optional("isbn", FieldType::String),
        FieldDef::optional("isbn13", FieldType::String),
        FieldDef::optional("language", FieldType::String),
        FieldDef::optional("license", FieldType::String),
        FieldDef::optional("novaGroup", FieldType::Integer),
        FieldDef::optional("nutritionScore", FieldType::String),
        FieldDef::optional("originalPrice", FieldType::String),
        FieldDef::optional("originalPriceAmount", FieldType::Number),
        FieldDef::optional("originalTitle", FieldType::String),
        FieldDef::optional("pages", FieldType::Integer),
        FieldDef::optional("places", FieldType::StringList),
        FieldDef::optional("price", FieldType::String),
        FieldDef::optional("priceAmount", FieldType::Number),
        FieldDef::optional("quantity", FieldType::Integer),
        FieldDef::optional("series", FieldType::String),
        FieldDef::optional("servingSize", FieldType::String),
        FieldDef::optional("sku", FieldType::String),
        FieldDef::optional("soldByWeight", FieldType::Boolean),
        FieldDef::optional("tags", FieldType::StringList),
        FieldDef::optional("weight", FieldType::String),
        FieldDef::optional("weightUnit", FieldType::String),
        FieldDef::optional("weightValue", FieldType::Number),
    ],
    out: vec![
        EdgeDef { label: "contributed_by".into(), to: Some("person".into()), from: None, card: Cardinality::Many },
    ],
    also: vec!["creative_work".into(), "product".into()],
    identity_any: vec!["isbn13".into(), "isbn".into()],
    display: Some(DisplaySpec {
        subtitle: Some("written_by".into()),
        image: Some("image".into()),
        body: Some("description".into()),
        highlights: vec!["datePublished".into(), "published_by".into()],
        ..DisplaySpec::default()
    }),
    ..ShapeDef::default()
});
