// DO NOT EDIT — generated from platform/ontology/shapes/booking_offer.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use super::sdk_prelude::*;

/// A signed, itemized, fully-priced commitment presented to a human for
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct BookingOffer {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub all_day: Option<bool>,
    pub approved_at: Option<String>,
    pub base_amount: Option<f64>,
    pub blob: Option<String>,
    pub cart_id: String,
    pub checkout_url: Option<String>,
    pub conditions: Option<serde_json::Value>,
    pub confirm_endpoint: Option<String>,
    pub contact_email: Option<String>,
    pub contact_phone: Option<String>,
    pub currency: Option<String>,
    pub current_url: Option<String>,
    pub date_updated: Option<String>,
    pub distinct_id: Option<String>,
    pub end_date: Option<String>,
    pub expires_at: Option<String>,
    pub fees_amount: Option<f64>,
    pub has_void_window: Option<bool>,
    pub ical_uid: Option<String>,
    pub is_changeable: Option<bool>,
    pub is_refundable: Option<bool>,
    pub itinerary_hash: Option<String>,
    pub prepared_at: Option<String>,
    pub presented_at: Option<String>,
    pub properties: Option<serde_json::Value>,
    pub recurrence: Option<Vec<String>>,
    pub reference_number: Option<String>,
    pub review: Option<String>,
    pub show_as: Option<String>,
    pub signature: Option<String>,
    pub signature_alg: Option<String>,
    pub signed_by: Option<String>,
    pub source_title: Option<String>,
    pub source_url: Option<String>,
    pub start_date: Option<String>,
    pub status: Option<String>,
    pub tax_amount: Option<f64>,
    pub timezone: Option<String>,
    pub total_amount: Option<f64>,
    pub visibility: Option<String>,
    pub void_window_ends_at: Option<String>,
}

pub static BOOKING_OFFER: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "booking_offer".into(),
    plural: Some("booking_offers".into()),
    description: Some("A signed, itemized, fully-priced commitment presented to a human for".into()),
    fields: vec![
        FieldDef::optional("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("allDay", FieldType::Boolean),
        FieldDef::optional("approvedAt", FieldType::Datetime),
        FieldDef::optional("baseAmount", FieldType::Number),
        FieldDef::optional("blob", FieldType::String),
        FieldDef::required("cartId", FieldType::String),
        FieldDef::optional("checkoutUrl", FieldType::Url),
        FieldDef::optional("conditions", FieldType::Json),
        FieldDef::optional("confirmEndpoint", FieldType::Url),
        FieldDef::optional("contactEmail", FieldType::String),
        FieldDef::optional("contactPhone", FieldType::String),
        FieldDef::optional("currency", FieldType::String),
        FieldDef::optional("currentUrl", FieldType::String),
        FieldDef::optional("dateUpdated", FieldType::Datetime),
        FieldDef::optional("distinctId", FieldType::String),
        FieldDef::optional("endDate", FieldType::Datetime),
        FieldDef::optional("expiresAt", FieldType::Datetime),
        FieldDef::optional("feesAmount", FieldType::Number),
        FieldDef::optional("hasVoidWindow", FieldType::Boolean),
        FieldDef::optional("icalUid", FieldType::String),
        FieldDef::optional("isChangeable", FieldType::Boolean),
        FieldDef::optional("isRefundable", FieldType::Boolean),
        FieldDef::optional("itineraryHash", FieldType::String),
        FieldDef::optional("preparedAt", FieldType::Datetime),
        FieldDef::optional("presentedAt", FieldType::Datetime),
        FieldDef::optional("properties", FieldType::Json),
        FieldDef::optional("recurrence", FieldType::StringList),
        FieldDef::optional("referenceNumber", FieldType::String),
        FieldDef::optional("review", FieldType::String),
        FieldDef::optional("showAs", FieldType::String),
        FieldDef::optional("signature", FieldType::String),
        FieldDef::optional("signatureAlg", FieldType::String),
        FieldDef::optional("signedBy", FieldType::String),
        FieldDef::optional("sourceTitle", FieldType::String),
        FieldDef::optional("sourceUrl", FieldType::Url),
        FieldDef::optional("startDate", FieldType::Datetime),
        FieldDef::optional("status", FieldType::String),
        FieldDef::optional("taxAmount", FieldType::Number),
        FieldDef::optional("timezone", FieldType::String),
        FieldDef::optional("totalAmount", FieldType::Number),
        FieldDef::optional("visibility", FieldType::String),
        FieldDef::optional("voidWindowEndsAt", FieldType::Datetime),
    ],
    also: vec!["event".into()],
    identity: vec!["at".into(), "cartId".into()],
    display: Some(DisplaySpec {
        subtitle: Some("totalAmount".into()),
        highlights: vec!["startDate".into(), "endDate".into(), "location".into()],
        ..DisplaySpec::default()
    }),
    prior_art: vec![
        PriorArtDef { source: "Duffel Offers API (pre-Order priced shape)".into(), url: Some("https://duffel.com/docs/api/offers/schema".into()), notes: Some("Duffel's Offer is the \"priced, held, about-to-become-an-order\" state. Our baseAmount/taxAmount/totalAmount/currency map to Duffel's base_amount/tax_amount/total_amount/total_currency; expiresAt = offer.expires_at. Duffel rolls taxes into a single aggregate — we split them into tax_line[] nodes.".into()) },
        PriorArtDef { source: "IATA NDC OfferPriceRQ / OfferPriceRS".into(), url: Some("https://developer.iata.org/en/ndc/".into()), notes: Some("NDC's OfferPrice is the mandatory \"price this exact shape with these exact passengers\" step between Shop and OrderCreate. Our guests[] mirror NDC's PaxList; taxLines[] mirror Taxes/ TaxSummary; signature mirrors OfferPriceRS's ShoppingResponseID that the airline expects back on OrderCreateRQ.".into()) },
        PriorArtDef { source: "Stripe Checkout Session".into(), url: Some("https://docs.stripe.com/api/checkout/sessions/object".into()), notes: Some("Canonical \"about-to-charge\" object. Our cartId ≈ session.id; expiresAt ≈ session.expires_at; totalAmount ≈ session.amount_total; paymentMethod relation mirrors session.payment_method. Stripe assumes line_item shape; we use domain-specific relations (trips/reservedItems) instead.".into()) },
        PriorArtDef { source: "Shopify Draft Order".into(), url: Some("https://shopify.dev/docs/api/admin-graphql/latest/objects/DraftOrder".into()), notes: Some("Shopify's non-binding pre-order — validates the \"cart with a reference number that can be invoiced and converted\" pattern. Our referenceNumber ≈ DraftOrder.name; becameReservation / becameTransaction mirror DraftOrder -> Order conversion.".into()) },
        PriorArtDef { source: "WebAuthn clientDataJSON + signed assertion".into(), url: Some("https://www.w3.org/TR/webauthn-3/".into()), notes: Some("Precedent for \"the thing the user saw is what got signed.\" WebAuthn signs (challenge, origin, type); we sign (cartId, itineraryHash, total, expiresAt). Our itineraryHash plays the role of WebAuthn's challenge — a commitment the verifier can match against the submitted shape.".into()) },
        PriorArtDef { source: "CoinGate Invoice (short-TTL priced blob)".into(), url: Some("https://developer.coingate.com/reference/order-statuses".into()), notes: Some("Validates the short-TTL pattern outside airlines. CoinGate invoices carry id, price locked ~20 min, and status (new, pending, paid, expired, canceled). Our status enum matches — pre-commit objects need expiry as a first-class terminal.".into()) },
        PriorArtDef { source: "schema.org/Order + schema.org/Invoice".into(), url: Some("https://schema.org/Order".into()), notes: Some("schema.org models Offer -> Order -> Invoice. booking_offer sits between Offer and Order — a priced, itemized, signed proposal awaiting explicit human commit. Our baseAmount + taxAmount + totalAmount align with UBL 2.1 LegalMonetaryTotal.".into()) },
    ],
    ..ShapeDef::default()
});
