// DO NOT EDIT — generated from platform/ontology/shapes/booking_offer.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use super::sdk_prelude::*;

/// A signed, itemized, fully-priced commitment presented to a human for
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct BookingOffer {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub all_day: Option<bool>,
    pub approved_at: Option<String>,
    pub base_amount: Option<f64>,
    pub blob: Option<String>,
    pub cart_id: String,
    pub checkout_url: Option<String>,
    pub conditions: Option<serde_json::Value>,
    pub confirm_endpoint: Option<String>,
    pub contact_email: Option<String>,
    pub contact_phone: Option<String>,
    pub currency: Option<String>,
    pub current_url: Option<String>,
    pub date_updated: Option<String>,
    pub distinct_id: Option<String>,
    pub end_date: Option<String>,
    pub expires_at: Option<String>,
    pub fees_amount: Option<f64>,
    pub has_void_window: Option<bool>,
    pub ical_uid: Option<String>,
    pub is_changeable: Option<bool>,
    pub is_refundable: Option<bool>,
    pub itinerary_hash: Option<String>,
    pub prepared_at: Option<String>,
    pub presented_at: Option<String>,
    pub properties: Option<serde_json::Value>,
    pub recurrence: Option<Vec<String>>,
    pub reference_number: Option<String>,
    pub review: Option<String>,
    pub show_as: Option<String>,
    pub signature: Option<String>,
    pub signature_alg: Option<String>,
    pub signed_by: Option<String>,
    pub source_title: Option<String>,
    pub source_url: Option<String>,
    pub start_date: Option<String>,
    pub status: Option<String>,
    pub tax_amount: Option<f64>,
    pub timezone: Option<String>,
    pub total_amount: Option<f64>,
    pub visibility: Option<String>,
    pub void_window_ends_at: Option<String>,
}

pub static BOOKING_OFFER: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "booking_offer".into(),
    plural: Some("booking_offers".into()),
    description: Some("A signed, itemized, fully-priced commitment presented to a human for".into()),
    fields: vec![
        FieldDef::optional("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("allDay", FieldType::Boolean),
        FieldDef::optional("approvedAt", FieldType::Datetime),
        FieldDef::optional("baseAmount", FieldType::Number),
        FieldDef::optional("blob", FieldType::String),
        FieldDef::required("cartId", FieldType::String),
        FieldDef::optional("checkoutUrl", FieldType::Url),
        FieldDef::optional("conditions", FieldType::Json),
        FieldDef::optional("confirmEndpoint", FieldType::Url),
        FieldDef::optional("contactEmail", FieldType::String),
        FieldDef::optional("contactPhone", FieldType::String),
        FieldDef::optional("currency", FieldType::String),
        FieldDef::optional("currentUrl", FieldType::String),
        FieldDef::optional("dateUpdated", FieldType::Datetime),
        FieldDef::optional("distinctId", FieldType::String),
        FieldDef::optional("endDate", FieldType::Datetime),
        FieldDef::optional("expiresAt", FieldType::Datetime),
        FieldDef::optional("feesAmount", FieldType::Number),
        FieldDef::optional("hasVoidWindow", FieldType::Boolean),
        FieldDef::optional("icalUid", FieldType::String),
        FieldDef::optional("isChangeable", FieldType::Boolean),
        FieldDef::optional("isRefundable", FieldType::Boolean),
        FieldDef::optional("itineraryHash", FieldType::String),
        FieldDef::optional("preparedAt", FieldType::Datetime),
        FieldDef::optional("presentedAt", FieldType::Datetime),
        FieldDef::optional("properties", FieldType::Json),
        FieldDef::optional("recurrence", FieldType::StringList),
        FieldDef::optional("referenceNumber", FieldType::String),
        FieldDef::optional("review", FieldType::String),
        FieldDef::optional("showAs", FieldType::String),
        FieldDef::optional("signature", FieldType::String),
        FieldDef::optional("signatureAlg", FieldType::String),
        FieldDef::optional("signedBy", FieldType::String),
        FieldDef::optional("sourceTitle", FieldType::String),
        FieldDef::optional("sourceUrl", FieldType::Url),
        FieldDef::optional("startDate", FieldType::Datetime),
        FieldDef::optional("status", FieldType::String),
        FieldDef::optional("taxAmount", FieldType::Number),
        FieldDef::optional("timezone", FieldType::String),
        FieldDef::optional("totalAmount", FieldType::Number),
        FieldDef::optional("visibility", FieldType::String),
        FieldDef::optional("voidWindowEndsAt", FieldType::Datetime),
    ],
    out: vec![
        EdgeDef { label: "at_namespace".into(), to: Some("actor".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "derived_from".into(), to: Some("offer".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "covers_trip".into(), to: Some("trip".into()), from: None, card: Cardinality::Many },
        EdgeDef { label: "reserves".into(), to: Some("pass".into()), from: None, card: Cardinality::Many },
        EdgeDef { label: "bought_by".into(), to: Some("person".into()), from: None, card: Cardinality::Many },
        EdgeDef { label: "accommodates".into(), to: Some("person".into()), from: None, card: Cardinality::Many },
        EdgeDef { label: "booked_for".into(), to: Some("person".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "paid_with".into(), to: Some("payment_method".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "billed_to".into(), to: Some("place".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "priced_at".into(), to: Some("fare".into()), from: None, card: Cardinality::Many },
        EdgeDef { label: "itemizes".into(), to: Some("tax_line".into()), from: None, card: Cardinality::Many },
        EdgeDef { label: "booked_under".into(), to: Some("account".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "tied_to".into(), to: Some("membership".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "brokered_by".into(), to: Some("actor".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "realized_as".into(), to: Some("reservation".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "settled_as".into(), to: Some("transaction".into()), from: None, card: Cardinality::One },
    ],
    also: vec!["event".into()],
    identity: vec!["at".into(), "cartId".into()],
    display: Some(DisplaySpec {
        subtitle: Some("totalAmount".into()),
        highlights: vec!["startDate".into(), "endDate".into(), "location".into()],
        ..DisplaySpec::default()
    }),
    ..ShapeDef::default()
});
