// DO NOT EDIT — generated from platform/ontology/shapes/device.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use super::sdk_prelude::*;

/// A specific networked device — a powered-on instance on a local network,
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct Device {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub aisle: Option<String>,
    pub availability: Option<String>,
    pub barcode: Option<String>,
    pub calories: Option<f64>,
    pub categories: Option<Vec<String>>,
    pub category: Option<String>,
    pub currency: Option<String>,
    pub customization_groups: Option<serde_json::Value>,
    pub department: Option<String>,
    pub discovered_via: Option<Vec<String>>,
    pub form_factor: Option<String>,
    pub hostname: Option<String>,
    pub images: Option<serde_json::Value>,
    pub ip_address: Option<String>,
    pub ipv6: Option<Vec<String>>,
    pub last_seen: Option<String>,
    pub location: Option<String>,
    pub mac_address: String,
    pub mac_randomized: Option<bool>,
    pub model: Option<String>,
    pub model_number: Option<String>,
    pub nova_group: Option<i64>,
    pub nutrition_score: Option<String>,
    pub online: Option<bool>,
    pub open_ports: Option<Vec<i64>>,
    pub original_price: Option<String>,
    pub original_price_amount: Option<f64>,
    pub price: Option<String>,
    pub price_amount: Option<f64>,
    pub quantity: Option<i64>,
    pub roles: Option<Vec<String>>,
    pub serving_size: Option<String>,
    pub sku: Option<String>,
    pub sold_by_weight: Option<bool>,
    pub vendor: Option<String>,
    pub weight: Option<String>,
    pub weight_unit: Option<String>,
    pub weight_value: Option<f64>,
}

pub static DEVICE: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "device".into(),
    plural: Some("devices".into()),
    description: Some("A specific networked device — a powered-on instance on a local network,".into()),
    fields: vec![
        FieldDef::optional("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("aisle", FieldType::String),
        FieldDef::optional("availability", FieldType::String),
        FieldDef::optional("barcode", FieldType::String),
        FieldDef::optional("calories", FieldType::Number),
        FieldDef::optional("categories", FieldType::StringList),
        FieldDef::optional("category", FieldType::String),
        FieldDef::optional("currency", FieldType::String),
        FieldDef::optional("customizationGroups", FieldType::Json),
        FieldDef::optional("department", FieldType::String),
        FieldDef::optional("discoveredVia", FieldType::StringList),
        FieldDef::optional("formFactor", FieldType::String),
        FieldDef::optional("hostname", FieldType::String),
        FieldDef::optional("images", FieldType::Json),
        FieldDef::optional("ipAddress", FieldType::String),
        FieldDef::optional("ipv6", FieldType::StringList),
        FieldDef::optional("lastSeen", FieldType::Datetime),
        FieldDef::optional("location", FieldType::String),
        FieldDef::required("macAddress", FieldType::String),
        FieldDef::optional("macRandomized", FieldType::Boolean),
        FieldDef::optional("model", FieldType::String),
        FieldDef::optional("modelNumber", FieldType::String),
        FieldDef::optional("novaGroup", FieldType::Integer),
        FieldDef::optional("nutritionScore", FieldType::String),
        FieldDef::optional("online", FieldType::Boolean),
        FieldDef::optional("openPorts", FieldType::IntegerList),
        FieldDef::optional("originalPrice", FieldType::String),
        FieldDef::optional("originalPriceAmount", FieldType::Number),
        FieldDef::optional("price", FieldType::String),
        FieldDef::optional("priceAmount", FieldType::Number),
        FieldDef::optional("quantity", FieldType::Integer),
        FieldDef::optional("roles", FieldType::StringList),
        FieldDef::optional("servingSize", FieldType::String),
        FieldDef::optional("sku", FieldType::String),
        FieldDef::optional("soldByWeight", FieldType::Boolean),
        FieldDef::optional("vendor", FieldType::String),
        FieldDef::optional("weight", FieldType::String),
        FieldDef::optional("weightUnit", FieldType::String),
        FieldDef::optional("weightValue", FieldType::Number),
    ],
    also: vec!["hardware".into()],
    identity: vec!["macAddress".into()],
    display: Some(DisplaySpec {
        subtitle: Some("ipAddress".into()),
        highlights: vec!["vendor".into(), "ipAddress".into(), "location".into()],
        ..DisplaySpec::default()
    }),
    prior_art: vec![
        PriorArtDef { source: "schema.org/IndividualProduct".into(), url: Some("https://schema.org/IndividualProduct".into()), notes: Some("A specific unit vs the ProductModel. macAddress is our stable identity (≈ serialNumber). Network/runtime state (ipAddress, online, ssid) has no schema.org equivalent — contextual, kept off the model.".into()) },
        PriorArtDef { source: "IEEE 802 EUI-48 (MAC) + IEEE OUI registry".into(), url: Some("https://standards.ieee.org/products-programs/regauth/".into()), notes: Some("macAddress is an EUI-48; the first 3 octets (OUI) resolve to the manufacturing organization. The locally-administered bit (2nd-LSB of the first octet) sets macRandomized.".into()) },
    ],
    ..ShapeDef::default()
});
