// DO NOT EDIT — generated from platform/ontology/shapes/email.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use super::sdk_prelude::*;

/// An email message. Emails are also messages — querying by "message"
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct Email {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub account_email: Option<String>,
    pub attachments: Option<serde_json::Value>,
    pub auth_results: Option<String>,
    pub bcc_raw: Option<String>,
    pub blocks: Option<serde_json::Value>,
    pub cc_raw: Option<String>,
    pub conversation_id: Option<String>,
    pub delivered_to: Option<String>,
    pub draft_id: Option<String>,
    pub has_attachments: Option<bool>,
    pub in_reply_to: Option<String>,
    pub is_automated: Option<bool>,
    pub is_group: Option<bool>,
    pub is_outgoing: Option<bool>,
    pub is_starred: Option<bool>,
    pub is_unread: Option<bool>,
    pub list_id: Option<String>,
    pub mailer: Option<String>,
    pub manage_subscription: Option<String>,
    pub message_id: Option<String>,
    pub precedence: Option<String>,
    pub references: Option<String>,
    pub reply_to: Option<String>,
    pub return_path: Option<String>,
    pub size_estimate: Option<i64>,
    pub subject: Option<String>,
    pub to_raw: Option<String>,
    pub unsubscribe: Option<String>,
    pub unsubscribe_one_click: Option<bool>,
}

pub static EMAIL: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "email".into(),
    plural: Some("emails".into()),
    description: Some("An email message. Emails are also messages — querying by \"message\"".into()),
    fields: vec![
        FieldDef::required("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("accountEmail", FieldType::String),
        FieldDef::optional("attachments", FieldType::Json),
        FieldDef::optional("authResults", FieldType::String),
        FieldDef::optional("bccRaw", FieldType::String),
        FieldDef::optional("blocks", FieldType::Json),
        FieldDef::optional("ccRaw", FieldType::String),
        FieldDef::optional("conversationId", FieldType::String),
        FieldDef::optional("deliveredTo", FieldType::String),
        FieldDef::optional("draftId", FieldType::String),
        FieldDef::optional("hasAttachments", FieldType::Boolean),
        FieldDef::optional("inReplyTo", FieldType::String),
        FieldDef::optional("isAutomated", FieldType::Boolean),
        FieldDef::optional("isGroup", FieldType::Boolean),
        FieldDef::optional("isOutgoing", FieldType::Boolean),
        FieldDef::optional("isStarred", FieldType::Boolean),
        FieldDef::optional("isUnread", FieldType::Boolean),
        FieldDef::optional("listId", FieldType::String),
        FieldDef::optional("mailer", FieldType::String),
        FieldDef::optional("manageSubscription", FieldType::String),
        FieldDef::optional("messageId", FieldType::String),
        FieldDef::optional("precedence", FieldType::String),
        FieldDef::optional("references", FieldType::String),
        FieldDef::optional("replyTo", FieldType::String),
        FieldDef::optional("returnPath", FieldType::String),
        FieldDef::optional("sizeEstimate", FieldType::Integer),
        FieldDef::optional("subject", FieldType::String),
        FieldDef::optional("toRaw", FieldType::String),
        FieldDef::optional("unsubscribe", FieldType::String),
        FieldDef::optional("unsubscribeOneClick", FieldType::Boolean),
    ],
    also: vec!["message".into()],
    account_from: Some("accountEmail".into()),
    membership: Some(agentos_graph::MembershipDef { service: "mailbox".into(), key: "mailbox".into() }),
    identity: vec!["at".into(), "id".into()],
    display: Some(DisplaySpec {
        subtitle: Some("author".into()),
        ..DisplaySpec::default()
    }),
    prior_art: vec![
        PriorArtDef { source: "RFC 5322 (Internet Message Format)".into(), url: Some("https://datatracker.ietf.org/doc/html/rfc5322".into()), notes: Some("Supersedes RFC 2822. Our messageId/inReplyTo/references/replyTo map directly to Message-ID/In-Reply-To/References/Reply-To headers; toRaw/ccRaw/bccRaw are the literal header values.".into()) },
        PriorArtDef { source: "RFC 2369 + RFC 8058 (List headers, one-click unsubscribe)".into(), url: Some("https://datatracker.ietf.org/doc/html/rfc2369".into()), notes: Some("Our unsubscribe/unsubscribeOneClick/listId are List-Unsubscribe/List-Unsubscribe-Post/List-ID. RFC 8058 defines the one-click POST semantics.".into()) },
        PriorArtDef { source: "Gmail API Message resource".into(), url: Some("https://developers.google.com/gmail/api/reference/rest/v1/users.messages".into()), notes: Some("Practical API mirror. Our sizeEstimate and isUnread/isStarred correspond to Gmail's sizeEstimate and the UNREAD/STARRED labels. The FOLDER labels (INBOX, TRASH, SPAM, SENT, DRAFT) are membership, not node flags — answered by the `mailbox` mirror-lists (`membership:` above), never stamped as as-of-last-sight booleans on the record.".into()) },
    ],
    ..ShapeDef::default()
});
