// DO NOT EDIT — generated from platform/ontology/shapes/health-reference-range.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use super::sdk_prelude::*;

/// A lab-specific reference interval — the "normal range" for a biomarker,
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct HealthReferenceRange {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub age_high: Option<f64>,
    pub age_low: Option<f64>,
    pub all_day: Option<bool>,
    pub category: Option<String>,
    pub current_url: Option<String>,
    pub date_updated: Option<String>,
    pub distinct_id: Option<String>,
    pub end_date: Option<String>,
    pub fasting: Option<bool>,
    pub gestational_age: Option<String>,
    pub high: Option<f64>,
    pub ical_uid: Option<String>,
    pub low: Option<f64>,
    pub method: String,
    pub pregnancy: Option<String>,
    pub properties: Option<serde_json::Value>,
    pub provenance: Option<String>,
    pub recurrence: Option<Vec<String>>,
    pub ref_text: Option<String>,
    pub sex: Option<String>,
    pub show_as: Option<String>,
    pub source_title: Option<String>,
    pub source_url: Option<String>,
    pub start_date: String,
    pub status: Option<String>,
    pub time_of_day: Option<String>,
    pub timezone: Option<String>,
    pub unit: Option<String>,
    pub visibility: Option<String>,
}

pub static HEALTH_REFERENCE_RANGE: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "health-reference-range".into(),
    plural: Some("health-reference-ranges".into()),
    description: Some("A lab-specific reference interval — the \"normal range\" for a biomarker,".into()),
    fields: vec![
        FieldDef::optional("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("ageHigh", FieldType::Number),
        FieldDef::optional("ageLow", FieldType::Number),
        FieldDef::optional("allDay", FieldType::Boolean),
        FieldDef::optional("category", FieldType::String),
        FieldDef::optional("currentUrl", FieldType::String),
        FieldDef::optional("dateUpdated", FieldType::Datetime),
        FieldDef::optional("distinctId", FieldType::String),
        FieldDef::optional("endDate", FieldType::Datetime),
        FieldDef::optional("fasting", FieldType::Boolean),
        FieldDef::optional("gestationalAge", FieldType::String),
        FieldDef::optional("high", FieldType::Number),
        FieldDef::optional("icalUid", FieldType::String),
        FieldDef::optional("low", FieldType::Number),
        FieldDef::required("method", FieldType::String),
        FieldDef::optional("pregnancy", FieldType::String),
        FieldDef::optional("properties", FieldType::Json),
        FieldDef::optional("provenance", FieldType::String),
        FieldDef::optional("recurrence", FieldType::StringList),
        FieldDef::optional("refText", FieldType::String),
        FieldDef::optional("sex", FieldType::String),
        FieldDef::optional("showAs", FieldType::String),
        FieldDef::optional("sourceTitle", FieldType::String),
        FieldDef::optional("sourceUrl", FieldType::Url),
        FieldDef::required("startDate", FieldType::Datetime),
        FieldDef::optional("status", FieldType::String),
        FieldDef::optional("timeOfDay", FieldType::String),
        FieldDef::optional("timezone", FieldType::String),
        FieldDef::optional("unit", FieldType::String),
        FieldDef::optional("visibility", FieldType::String),
    ],
    also: vec!["event".into()],
    identity: vec!["analyte".into(), "issuingLab".into(), "method".into(), "startDate".into()],
    display: Some(DisplaySpec {
        subtitle: Some("refText".into()),
        highlights: vec!["startDate".into(), "endDate".into(), "location".into()],
        ..DisplaySpec::default()
    }),
    prior_art: vec![
        PriorArtDef { source: "CLSI EP28-A3c — Defining, Establishing, and Verifying Reference Intervals".into(), url: Some("https://clsi.org/shop/standards/ep28/".into()), notes: Some("The authoritative protocol. Each lab must establish (de novo, min n=120 per partition) or verify (min n=20) its own intervals. `provenance` (established/verified/manufacturer-claimed) comes directly from this guideline; it is why two same-instrument labs legitimately diverge.".into()) },
        PriorArtDef { source: "HL7 FHIR R5 — ObservationDefinition.qualifiedInterval".into(), url: Some("https://www.hl7.org/fhir/observationdefinition.html".into()), notes: Some("The closest standard precedent — a reusable, multi-context interval. Our category maps to its rangeCategory; range to range; age/gestationalAge/sex to the same; condition ≈ our population fields. But qualifiedInterval has NO issuingLab and NO validity window — this shape adds both. qualifiedInterval is the lossy EXPORT projection of this shape, not its equal.".into()) },
        PriorArtDef { source: "HL7 FHIR R5 — Observation.referenceRange".into(), url: Some("https://www.hl7.org/fhir/observation.html".into()), notes: Some("FHIR's other reference-range model — inlined on the result as a denormalized snapshot (low/high/normalValue/type/appliesTo/age/ text). health-observation keeps that snapshot too (its refLow/ refHigh fields); this shape is the normalized, reusable form the snapshot can point back to.".into()) },
        PriorArtDef { source: "OMOP CDM v5.4 — MEASUREMENT.range_low / range_high".into(), url: Some("https://ohdsi.github.io/CommonDataModel/cdm54.html".into()), notes: Some("OMOP inlines range_low/range_high as columns on the measurement row — \"no separate standalone table for reference ranges.\" Confirms the gap: no major model makes the range first-class.".into()) },
    ],
    ..ShapeDef::default()
});
