// DO NOT EDIT — generated from platform/ontology/shapes/health-reference-range.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use agentos_graph::{
    Cardinality, DerivedBinding, DisplaySpec, EdgeDef, FieldDef, FieldType,
    ShapeDef, ShortcutDef,
};
use once_cell::sync::Lazy;
use serde::{Deserialize, Serialize};

/// A lab-specific reference interval — the "normal range" for a biomarker,
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct HealthReferenceRange {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub age_high: Option<f64>,
    pub age_low: Option<f64>,
    pub all_day: Option<bool>,
    pub category: Option<String>,
    pub current_url: Option<String>,
    pub date_updated: Option<String>,
    pub distinct_id: Option<String>,
    pub end_date: Option<String>,
    pub fasting: Option<bool>,
    pub gestational_age: Option<String>,
    pub high: Option<f64>,
    pub ical_uid: Option<String>,
    pub low: Option<f64>,
    pub method: String,
    pub pregnancy: Option<String>,
    pub properties: Option<serde_json::Value>,
    pub provenance: Option<String>,
    pub recurrence: Option<Vec<String>>,
    pub ref_text: Option<String>,
    pub sex: Option<String>,
    pub show_as: Option<String>,
    pub source_title: Option<String>,
    pub source_url: Option<String>,
    pub start_date: String,
    pub status: Option<String>,
    pub time_of_day: Option<String>,
    pub timezone: Option<String>,
    pub unit: Option<String>,
    pub visibility: Option<String>,
}

pub static HEALTH_REFERENCE_RANGE: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "health-reference-range".into(),
    plural: Some("health-reference-ranges".into()),
    description: Some("A lab-specific reference interval — the \"normal range\" for a biomarker,".into()),
    fields: vec![
        FieldDef::optional("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("ageHigh", FieldType::Number),
        FieldDef::optional("ageLow", FieldType::Number),
        FieldDef::optional("allDay", FieldType::Boolean),
        FieldDef::optional("category", FieldType::String),
        FieldDef::optional("currentUrl", FieldType::String),
        FieldDef::optional("dateUpdated", FieldType::Datetime),
        FieldDef::optional("distinctId", FieldType::String),
        FieldDef::optional("endDate", FieldType::Datetime),
        FieldDef::optional("fasting", FieldType::Boolean),
        FieldDef::optional("gestationalAge", FieldType::String),
        FieldDef::optional("high", FieldType::Number),
        FieldDef::optional("icalUid", FieldType::String),
        FieldDef::optional("low", FieldType::Number),
        FieldDef::required("method", FieldType::String),
        FieldDef::optional("pregnancy", FieldType::String),
        FieldDef::optional("properties", FieldType::Json),
        FieldDef::optional("provenance", FieldType::String),
        FieldDef::optional("recurrence", FieldType::StringList),
        FieldDef::optional("refText", FieldType::String),
        FieldDef::optional("sex", FieldType::String),
        FieldDef::optional("showAs", FieldType::String),
        FieldDef::optional("sourceTitle", FieldType::String),
        FieldDef::optional("sourceUrl", FieldType::Url),
        FieldDef::required("startDate", FieldType::Datetime),
        FieldDef::optional("status", FieldType::String),
        FieldDef::optional("timeOfDay", FieldType::String),
        FieldDef::optional("timezone", FieldType::String),
        FieldDef::optional("unit", FieldType::String),
        FieldDef::optional("visibility", FieldType::String),
    ],
    also: vec!["event".into()],
    identity: vec!["analyte".into(), "issuingLab".into(), "method".into(), "startDate".into()],
    display: Some(DisplaySpec {
        subtitle: Some("refText".into()),
        highlights: vec!["startDate".into(), "endDate".into(), "location".into()],
        ..DisplaySpec::default()
    }),
    ..ShapeDef::default()
});
