// DO NOT EDIT — generated from platform/ontology/shapes/insurance_policy.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use super::sdk_prelude::*;

/// A contract of indemnity — one party (the insured) pays premiums to a
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct InsurancePolicy {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub all_day: Option<bool>,
    pub auto_renew: Option<bool>,
    pub billing_type: Option<String>,
    pub coverage_type: Option<String>,
    pub currency: Option<String>,
    pub current_url: Option<String>,
    pub date_updated: Option<String>,
    pub distinct_id: Option<String>,
    pub end_date: Option<String>,
    pub group_number: Option<String>,
    pub guest_pass_quantity: Option<i64>,
    pub ical_uid: Option<String>,
    pub member_id: Option<String>,
    pub network: Option<String>,
    pub policy_number: String,
    pub price: Option<f64>,
    pub properties: Option<serde_json::Value>,
    pub recurrence: Option<Vec<String>>,
    pub show_as: Option<String>,
    pub source_title: Option<String>,
    pub source_url: Option<String>,
    pub start_date: Option<String>,
    pub status: Option<String>,
    pub tier: Option<String>,
    pub timezone: Option<String>,
    pub use_count: Option<i64>,
    pub visibility: Option<String>,
}

pub static INSURANCE_POLICY: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "insurance_policy".into(),
    plural: Some("insurance_policies".into()),
    description: Some("A contract of indemnity — one party (the insured) pays premiums to a".into()),
    fields: vec![
        FieldDef::optional("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("allDay", FieldType::Boolean),
        FieldDef::optional("autoRenew", FieldType::Boolean),
        FieldDef::optional("billingType", FieldType::String),
        FieldDef::optional("coverageType", FieldType::String),
        FieldDef::optional("currency", FieldType::String),
        FieldDef::optional("currentUrl", FieldType::String),
        FieldDef::optional("dateUpdated", FieldType::Datetime),
        FieldDef::optional("distinctId", FieldType::String),
        FieldDef::optional("endDate", FieldType::Datetime),
        FieldDef::optional("groupNumber", FieldType::String),
        FieldDef::optional("guestPassQuantity", FieldType::Integer),
        FieldDef::optional("icalUid", FieldType::String),
        FieldDef::optional("memberId", FieldType::String),
        FieldDef::optional("network", FieldType::String),
        FieldDef::required("policyNumber", FieldType::String),
        FieldDef::optional("price", FieldType::Number),
        FieldDef::optional("properties", FieldType::Json),
        FieldDef::optional("recurrence", FieldType::StringList),
        FieldDef::optional("showAs", FieldType::String),
        FieldDef::optional("sourceTitle", FieldType::String),
        FieldDef::optional("sourceUrl", FieldType::Url),
        FieldDef::optional("startDate", FieldType::Datetime),
        FieldDef::optional("status", FieldType::String),
        FieldDef::optional("tier", FieldType::String),
        FieldDef::optional("timezone", FieldType::String),
        FieldDef::optional("useCount", FieldType::Integer),
        FieldDef::optional("visibility", FieldType::String),
    ],
    also: vec!["membership".into()],
    identity: vec!["underwritten_by".into(), "policyNumber".into()],
    display: Some(DisplaySpec {
        subtitle: Some("coverageType".into()),
        highlights: vec!["startDate".into(), "endDate".into(), "location".into()],
        ..DisplaySpec::default()
    }),
    prior_art: vec![
        PriorArtDef { source: "HL7 FHIR R5 — Coverage".into(), url: Some("https://www.hl7.org/fhir/coverage.html".into()), notes: Some("The canonical health-insurance enrollment resource. Our memberId ≈ Coverage.subscriberId / Coverage.beneficiary; groupNumber ≈ Coverage.class[type=group]; underwritten_by ≈ Coverage.payor; under (plan) ≈ Coverage.class[type=plan]; network ≈ Coverage.network. Coverage.period maps to our inherited event.startDate / endDate.".into()) },
        PriorArtDef { source: "HL7 FHIR R5 — InsurancePlan".into(), url: Some("https://www.hl7.org/fhir/insuranceplan.html".into()), notes: Some("Describes the PLAN (the product), distinct from a person's Coverage. We split the same way — the plan is a `product` reached via `under`; InsurancePlan.coverage[].benefit (limits, cost-sharing) is our `insurance_coverage` nodes reached via `provides`.".into()) },
        PriorArtDef { source: "ACORD Reference Architecture — Policy / Coverage / Producer".into(), url: Some("https://www.acord.org/standards-architecture/reference-architecture".into()), notes: Some("The P&C industry data standard. ACORD separates Insurer (carrier), Producer (agent/broker who sells), and Policy → Coverage → Limit / Deductible. Our underwritten_by ≈ Insurer, sold_by ≈ Producer, and insurance_coverage ≈ ACORD Coverage with its Limit/Deductible.".into()) },
        PriorArtDef { source: "schema.org/ProgramMembership & schema.org/Permit".into(), url: Some("https://schema.org/ProgramMembership".into()), notes: Some("schema.org has no first-class insurance policy type; the closest framing is a membership/permit granted by an organization for a period — which is exactly why we model the policy as `also: [membership]` rather than inventing a parallel lifecycle.".into()) },
    ],
    ..ShapeDef::default()
});
