// DO NOT EDIT — generated from platform/ontology/shapes/launch.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use super::sdk_prelude::*;

/// A rocket launch event. Carries flight-specific fields that previously
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct Launch {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub all_day: Option<bool>,
    pub article_url: Option<String>,
    pub crew_ids: Option<Vec<String>>,
    pub current_url: Option<String>,
    pub date_updated: Option<String>,
    pub distinct_id: Option<String>,
    pub end_date: Option<String>,
    pub flight_number: Option<i64>,
    pub ical_uid: Option<String>,
    pub landing_outcomes: Option<serde_json::Value>,
    pub launchpad_id: Option<String>,
    pub patch_image: Option<String>,
    pub properties: Option<serde_json::Value>,
    pub recurrence: Option<Vec<String>>,
    pub reused_boosters: Option<Vec<String>>,
    pub rocket_id: Option<String>,
    pub show_as: Option<String>,
    pub source_title: Option<String>,
    pub source_url: Option<String>,
    pub start_date: Option<String>,
    pub status: Option<String>,
    pub timezone: Option<String>,
    pub visibility: Option<String>,
    pub webcast_url: Option<String>,
    pub wikipedia_url: Option<String>,
}

pub static LAUNCH: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "launch".into(),
    plural: Some("launches".into()),
    description: Some("A rocket launch event. Carries flight-specific fields that previously".into()),
    fields: vec![
        FieldDef::optional("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("allDay", FieldType::Boolean),
        FieldDef::optional("articleUrl", FieldType::Url),
        FieldDef::optional("crewIds", FieldType::StringList),
        FieldDef::optional("currentUrl", FieldType::String),
        FieldDef::optional("dateUpdated", FieldType::Datetime),
        FieldDef::optional("distinctId", FieldType::String),
        FieldDef::optional("endDate", FieldType::Datetime),
        FieldDef::optional("flightNumber", FieldType::Integer),
        FieldDef::optional("icalUid", FieldType::String),
        FieldDef::optional("landingOutcomes", FieldType::Json),
        FieldDef::optional("launchpadId", FieldType::String),
        FieldDef::optional("patchImage", FieldType::Url),
        FieldDef::optional("properties", FieldType::Json),
        FieldDef::optional("recurrence", FieldType::StringList),
        FieldDef::optional("reusedBoosters", FieldType::StringList),
        FieldDef::optional("rocketId", FieldType::String),
        FieldDef::optional("showAs", FieldType::String),
        FieldDef::optional("sourceTitle", FieldType::String),
        FieldDef::optional("sourceUrl", FieldType::Url),
        FieldDef::optional("startDate", FieldType::Datetime),
        FieldDef::optional("status", FieldType::String),
        FieldDef::optional("timezone", FieldType::String),
        FieldDef::optional("visibility", FieldType::String),
        FieldDef::optional("webcastUrl", FieldType::Url),
        FieldDef::optional("wikipediaUrl", FieldType::Url),
    ],
    also: vec!["event".into()],
    display: Some(DisplaySpec {
        subtitle: Some("rocketId".into()),
        highlights: vec!["startDate".into(), "rocketId".into(), "launchpadId".into()],
        ..DisplaySpec::default()
    }),
    ..ShapeDef::default()
});
