// DO NOT EDIT — generated from platform/ontology/shapes/*.yaml.
// Regen: `python3 platform/codegen/generate.py`.

#![allow(non_upper_case_globals)]

// Curated prelude for the generated shape files. Every shape file does
// `use super::sdk_prelude::*;` — one canonical import line, no per-file
// symbol list, no namespace leakage from mod.rs's own lookup machinery
// below (PreviewPolicy, Display, lookup_*, etc). Standard Rust idiom:
// `serde::prelude`, `clap::prelude`, `bevy::prelude::*` all work this way.
//
// Symbol set is derived from the ontology — only the types at least one
// shape references are re-exported, so an unused-import warning here is
// impossible by construction.
pub(crate) mod sdk_prelude {
    pub(crate) use agentos_graph::{
        DerivedBinding, DisplaySpec, FieldDef, FieldGroupDef, FieldType, PriorArtDef, ShapeDef,
    };
    pub(crate) use once_cell::sync::Lazy;
    pub(crate) use serde::{Deserialize, Serialize};
}

pub mod account;
pub mod activity;
pub mod actor;
pub mod aircraft;
pub mod airline;
pub mod airport;
pub mod app;
pub mod auth_challenge;
pub mod book;
pub mod booking_offer;
pub mod bookmark;
pub mod branch;
pub mod brand;
pub mod browser;
pub mod calendar;
pub mod channel;
pub mod class;
pub mod community;
pub mod concern;
pub mod conversation;
pub mod conversion;
pub mod creative_work;
pub mod cursor;
pub mod device;
pub mod dimension;
pub mod dns_record;
pub mod document;
pub mod domain;
pub mod email;
pub mod episode;
pub mod event;
pub mod fare;
pub mod file;
pub mod financial_account;
pub mod flight;
pub mod font;
pub mod git_commit;
pub mod group;
pub mod hardware;
pub mod health_biomarker;
pub mod health_condition;
pub mod health_immunization;
pub mod health_lab;
pub mod health_panel;
pub mod health_procedure;
pub mod health_reference_range;
pub mod icon;
pub mod image;
pub mod insurance_coverage;
pub mod insurance_policy;
pub mod intellectual_property;
pub mod invitation;
pub mod issue;
pub mod launch;
pub mod leg;
pub mod list;
pub mod loaded_model;
pub mod mcp_session;
pub mod measure;
pub mod meeting;
pub mod membership;
pub mod message;
pub mod model;
pub mod module;
pub mod network;
pub mod note;
pub mod offer;
pub mod order;
pub mod organization;
pub mod outcome;
pub mod pass;
pub mod payment_method;
pub mod person;
pub mod persona;
pub mod place;
pub mod platform;
pub mod playlist;
pub mod plugin;
pub mod podcast;
pub mod post;
pub mod practice;
pub mod principle;
pub mod product;
pub mod project;
pub mod protocol;
pub mod qualification;
pub mod quantity_kind;
pub mod quote;
pub mod repository;
pub mod reservation;
pub mod result;
pub mod review;
pub mod role;
pub mod seatmap;
pub mod service;
pub mod settings;
pub mod shape;
pub mod shelf;
pub mod software;
pub mod sound;
pub mod source;
pub mod spec;
pub mod subscription;
pub mod symbol;
pub mod tag;
pub mod task;
pub mod tax_line;
pub mod theme;
pub mod tool_call;
pub mod transaction;
pub mod transcript;
pub mod treatment;
pub mod trip;
pub mod unit;
pub mod user;
pub mod user_identity;
pub mod video;
pub mod volume;
pub mod vote;
pub mod website;

pub use account::{ACCOUNT, Account};
pub use activity::{ACTIVITY, Activity};
pub use actor::{ACTOR, Actor};
pub use aircraft::{AIRCRAFT, Aircraft};
pub use airline::{AIRLINE, Airline};
pub use airport::{AIRPORT, Airport};
pub use app::{APP, App};
pub use auth_challenge::{AUTH_CHALLENGE, AuthChallenge};
pub use book::{BOOK, Book};
pub use booking_offer::{BOOKING_OFFER, BookingOffer};
pub use bookmark::{BOOKMARK, Bookmark};
pub use branch::{BRANCH, Branch};
pub use brand::{BRAND, Brand};
pub use browser::{BROWSER, Browser};
pub use calendar::{CALENDAR, Calendar};
pub use channel::{CHANNEL, Channel};
pub use class::{CLASS, Class};
pub use community::{COMMUNITY, Community};
pub use concern::{CONCERN, Concern};
pub use conversation::{CONVERSATION, Conversation};
pub use conversion::{CONVERSION, Conversion};
pub use creative_work::{CREATIVE_WORK, CreativeWork};
pub use cursor::{CURSOR, Cursor};
pub use device::{DEVICE, Device};
pub use dimension::{DIMENSION, Dimension};
pub use dns_record::{DNS_RECORD, DnsRecord};
pub use document::{DOCUMENT, Document};
pub use domain::{DOMAIN, Domain};
pub use email::{EMAIL, Email};
pub use episode::{EPISODE, Episode};
pub use event::{EVENT, Event};
pub use fare::{FARE, Fare};
pub use file::{FILE, File};
pub use financial_account::{FINANCIAL_ACCOUNT, FinancialAccount};
pub use flight::{FLIGHT, Flight};
pub use font::{FONT, Font};
pub use git_commit::{GIT_COMMIT, GitCommit};
pub use group::{GROUP, Group};
pub use hardware::{HARDWARE, Hardware};
pub use health_biomarker::{HEALTH_BIOMARKER, HealthBiomarker};
pub use health_condition::{HEALTH_CONDITION, HealthCondition};
pub use health_immunization::{HEALTH_IMMUNIZATION, HealthImmunization};
pub use health_lab::{HEALTH_LAB, HealthLab};
pub use health_panel::{HEALTH_PANEL, HealthPanel};
pub use health_procedure::{HEALTH_PROCEDURE, HealthProcedure};
pub use health_reference_range::{HEALTH_REFERENCE_RANGE, HealthReferenceRange};
pub use icon::{ICON, Icon};
pub use image::{IMAGE, Image};
pub use insurance_coverage::{INSURANCE_COVERAGE, InsuranceCoverage};
pub use insurance_policy::{INSURANCE_POLICY, InsurancePolicy};
pub use intellectual_property::{INTELLECTUAL_PROPERTY, IntellectualProperty};
pub use invitation::{INVITATION, Invitation};
pub use issue::{ISSUE, Issue};
pub use launch::{LAUNCH, Launch};
pub use leg::{LEG, Leg};
pub use list::{LIST, List};
pub use loaded_model::{LOADED_MODEL, LoadedModel};
pub use mcp_session::{MCP_SESSION, McpSession};
pub use measure::{MEASURE, Measure};
pub use meeting::{MEETING, Meeting};
pub use membership::{MEMBERSHIP, Membership};
pub use message::{MESSAGE, Message};
pub use model::{MODEL, Model};
pub use module::{MODULE, Module};
pub use network::{NETWORK, Network};
pub use note::{NOTE, Note};
pub use offer::{OFFER, Offer};
pub use order::{ORDER, Order};
pub use organization::{ORGANIZATION, Organization};
pub use outcome::{OUTCOME, Outcome};
pub use pass::{PASS, Pass};
pub use payment_method::{PAYMENT_METHOD, PaymentMethod};
pub use person::{PERSON, Person};
pub use persona::{PERSONA, Persona};
pub use place::{PLACE, Place};
pub use platform::{PLATFORM, Platform};
pub use playlist::{PLAYLIST, Playlist};
pub use plugin::{PLUGIN, Plugin};
pub use podcast::{PODCAST, Podcast};
pub use post::{POST, Post};
pub use practice::{PRACTICE, Practice};
pub use principle::{PRINCIPLE, Principle};
pub use product::{PRODUCT, Product};
pub use project::{PROJECT, Project};
pub use protocol::{PROTOCOL, Protocol};
pub use qualification::{QUALIFICATION, Qualification};
pub use quantity_kind::{QUANTITY_KIND, QuantityKind};
pub use quote::{QUOTE, Quote};
pub use repository::{REPOSITORY, Repository};
pub use reservation::{RESERVATION, Reservation};
pub use result::{RESULT, Result};
pub use review::{REVIEW, Review};
pub use role::{ROLE, Role};
pub use seatmap::{SEATMAP, Seatmap};
pub use service::{SERVICE, Service};
pub use settings::{SETTINGS, Settings};
pub use shape::{SHAPE, Shape};
pub use shelf::{SHELF, Shelf};
pub use software::{SOFTWARE, Software};
pub use sound::{SOUND, Sound};
pub use source::{SOURCE, Source};
pub use spec::{SPEC, Spec};
pub use subscription::{SUBSCRIPTION, Subscription};
pub use symbol::{SYMBOL, Symbol};
pub use tag::{TAG, Tag};
pub use task::{TASK, Task};
pub use tax_line::{TAX_LINE, TaxLine};
pub use theme::{THEME, Theme};
pub use tool_call::{TOOL_CALL, ToolCall};
pub use transaction::{TRANSACTION, Transaction};
pub use transcript::{TRANSCRIPT, Transcript};
pub use treatment::{TREATMENT, Treatment};
pub use trip::{TRIP, Trip};
pub use unit::{UNIT, Unit};
pub use user::{USER, User};
pub use user_identity::{USER_IDENTITY, UserIdentity};
pub use video::{VIDEO, Video};
pub use volume::{VOLUME, Volume};
pub use vote::{VOTE, Vote};
pub use website::{WEBSITE, Website};

// ===========================================================
// Def lookup — full compiled ShapeDef by shape name
// ===========================================================

pub fn lookup_def(shape: &str) -> Option<&'static agentos_graph::ShapeDef> {
    match shape {
        "account" => Some(&ACCOUNT),
        "activity" => Some(&ACTIVITY),
        "actor" => Some(&ACTOR),
        "aircraft" => Some(&AIRCRAFT),
        "airline" => Some(&AIRLINE),
        "airport" => Some(&AIRPORT),
        "app" => Some(&APP),
        "auth_challenge" => Some(&AUTH_CHALLENGE),
        "book" => Some(&BOOK),
        "booking_offer" => Some(&BOOKING_OFFER),
        "bookmark" => Some(&BOOKMARK),
        "branch" => Some(&BRANCH),
        "brand" => Some(&BRAND),
        "browser" => Some(&BROWSER),
        "calendar" => Some(&CALENDAR),
        "channel" => Some(&CHANNEL),
        "class" => Some(&CLASS),
        "community" => Some(&COMMUNITY),
        "concern" => Some(&CONCERN),
        "conversation" => Some(&CONVERSATION),
        "conversion" => Some(&CONVERSION),
        "creative_work" => Some(&CREATIVE_WORK),
        "cursor" => Some(&CURSOR),
        "device" => Some(&DEVICE),
        "dimension" => Some(&DIMENSION),
        "dns_record" => Some(&DNS_RECORD),
        "document" => Some(&DOCUMENT),
        "domain" => Some(&DOMAIN),
        "email" => Some(&EMAIL),
        "episode" => Some(&EPISODE),
        "event" => Some(&EVENT),
        "fare" => Some(&FARE),
        "file" => Some(&FILE),
        "financial_account" => Some(&FINANCIAL_ACCOUNT),
        "flight" => Some(&FLIGHT),
        "font" => Some(&FONT),
        "git_commit" => Some(&GIT_COMMIT),
        "group" => Some(&GROUP),
        "hardware" => Some(&HARDWARE),
        "health-biomarker" => Some(&HEALTH_BIOMARKER),
        "health-condition" => Some(&HEALTH_CONDITION),
        "health-immunization" => Some(&HEALTH_IMMUNIZATION),
        "health-lab" => Some(&HEALTH_LAB),
        "health-panel" => Some(&HEALTH_PANEL),
        "health-procedure" => Some(&HEALTH_PROCEDURE),
        "health-reference-range" => Some(&HEALTH_REFERENCE_RANGE),
        "icon" => Some(&ICON),
        "image" => Some(&IMAGE),
        "insurance_coverage" => Some(&INSURANCE_COVERAGE),
        "insurance_policy" => Some(&INSURANCE_POLICY),
        "intellectual_property" => Some(&INTELLECTUAL_PROPERTY),
        "invitation" => Some(&INVITATION),
        "issue" => Some(&ISSUE),
        "launch" => Some(&LAUNCH),
        "leg" => Some(&LEG),
        "list" => Some(&LIST),
        "loaded_model" => Some(&LOADED_MODEL),
        "mcp_session" => Some(&MCP_SESSION),
        "measure" => Some(&MEASURE),
        "meeting" => Some(&MEETING),
        "membership" => Some(&MEMBERSHIP),
        "message" => Some(&MESSAGE),
        "model" => Some(&MODEL),
        "module" => Some(&MODULE),
        "network" => Some(&NETWORK),
        "note" => Some(&NOTE),
        "offer" => Some(&OFFER),
        "order" => Some(&ORDER),
        "organization" => Some(&ORGANIZATION),
        "outcome" => Some(&OUTCOME),
        "pass" => Some(&PASS),
        "payment_method" => Some(&PAYMENT_METHOD),
        "person" => Some(&PERSON),
        "persona" => Some(&PERSONA),
        "place" => Some(&PLACE),
        "platform" => Some(&PLATFORM),
        "playlist" => Some(&PLAYLIST),
        "plugin" => Some(&PLUGIN),
        "podcast" => Some(&PODCAST),
        "post" => Some(&POST),
        "practice" => Some(&PRACTICE),
        "principle" => Some(&PRINCIPLE),
        "product" => Some(&PRODUCT),
        "project" => Some(&PROJECT),
        "protocol" => Some(&PROTOCOL),
        "qualification" => Some(&QUALIFICATION),
        "quantity-kind" => Some(&QUANTITY_KIND),
        "quote" => Some(&QUOTE),
        "repository" => Some(&REPOSITORY),
        "reservation" => Some(&RESERVATION),
        "result" => Some(&RESULT),
        "review" => Some(&REVIEW),
        "role" => Some(&ROLE),
        "seatmap" => Some(&SEATMAP),
        "service" => Some(&SERVICE),
        "settings" => Some(&SETTINGS),
        "shape" => Some(&SHAPE),
        "shelf" => Some(&SHELF),
        "software" => Some(&SOFTWARE),
        "sound" => Some(&SOUND),
        "source" => Some(&SOURCE),
        "spec" => Some(&SPEC),
        "subscription" => Some(&SUBSCRIPTION),
        "symbol" => Some(&SYMBOL),
        "tag" => Some(&TAG),
        "task" => Some(&TASK),
        "tax_line" => Some(&TAX_LINE),
        "theme" => Some(&THEME),
        "tool_call" => Some(&TOOL_CALL),
        "transaction" => Some(&TRANSACTION),
        "transcript" => Some(&TRANSCRIPT),
        "treatment" => Some(&TREATMENT),
        "trip" => Some(&TRIP),
        "unit" => Some(&UNIT),
        "user" => Some(&USER),
        "user_identity" => Some(&USER_IDENTITY),
        "video" => Some(&VIDEO),
        "volume" => Some(&VOLUME),
        "vote" => Some(&VOTE),
        "website" => Some(&WEBSITE),
        _ => None,
    }
}

// ===========================================================
// Display specs — `display:` block per shape
// ===========================================================

/// Per-field clip policy at preview/card density.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PreviewPolicy {
    Clip,
    Full,
    MaxChars(usize),
}

/// The preview card's header composition — a bound portrait field whose
/// shape/size are a CLOSED enum resolving to theme tokens (never raw px).
#[derive(Debug, Clone)]
pub struct Media {
    pub field: &'static str,
    pub shape: Option<&'static str>,
    pub size: Option<&'static str>,
}

/// The closed roles every theme + renderer projects against.
#[derive(Debug, Clone)]
pub struct Display {
    pub title: Option<&'static str>,
    pub subtitle: Option<&'static str>,
    pub image: Option<&'static str>,
    pub highlights: &'static [&'static str],
    pub body: Option<&'static str>,
    pub mono: Option<&'static str>,
    pub preview: &'static [(&'static str, PreviewPolicy)],
    pub also: &'static [&'static str],
    /// Material glyph for this shape's face (`display.icon`). The icon
    /// resolver picks the most-specific shape carrying one; its slug is
    /// the stamped `iconRole`, and the floor maps slug → this glyph.
    pub icon: Option<&'static str>,
    /// `display.iconFrom` — an enum field whose value IS the per-record
    /// icon slot (device.formFactor → router/tv/…). Resolved engine-side.
    pub icon_from: Option<&'static str>,
    /// `display.labels` — per-field display-label overrides for the preview
    /// card (e.g. `price` → "premium"); the humanized field name is the default.
    pub labels: &'static [(&'static str, &'static str)],
    /// `display.media` — the contact-card portrait binding + shape/size enums.
    pub media: Option<Media>,
    /// `display.lines` — promoted header lines under the title.
    pub lines: &'static [&'static str],
}

pub fn lookup_display(shape: &str) -> Option<&'static Display> {
    SHAPE_DISPLAY.iter().find(|(name, _)| *name == shape).map(|(_, d)| d)
}

/// Per-shape display-label override (`display.labels`) — the humanized field
/// name is the default when a field is absent from the returned slice.
pub fn lookup_label(shape: &str, field: &str) -> Option<&'static str> {
    lookup_display(shape)
        .and_then(|d| d.labels.iter().find(|(k, _)| *k == field).map(|(_, v)| *v))
}

pub static SHAPE_DISPLAY: &[(&'static str, Display)] = &[
    ("account", Display {
        title: None,
        subtitle: Some("identifier"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("alternate_email"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("activity", Display {
        title: None,
        subtitle: Some("action"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("timeline"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("actor", Display {
        title: None,
        subtitle: Some("actorType"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("theater_comedy"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("aircraft", Display {
        title: None,
        subtitle: Some("model"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &["product"],
        icon: Some("flight"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("airline", Display {
        title: None,
        subtitle: Some("iataCode"),
        image: Some("image"),
        highlights: &["headquarters"],
        body: None,
        mono: None,
        preview: &[],
        also: &["organization", "actor"],
        icon: Some("airlines"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("airport", Display {
        title: None,
        subtitle: Some("iataCode"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("flight_takeoff"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("app", Display {
        title: None,
        subtitle: Some("description"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("web_asset"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("auth_challenge", Display {
        title: None,
        subtitle: Some("instructions"),
        image: None,
        highlights: &[],
        body: Some("artifact"),
        mono: Some("artifact"),
        preview: &[("artifact", PreviewPolicy::Full)],
        also: &[],
        icon: Some("qr_code_2"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("book", Display {
        title: None,
        subtitle: Some("written_by"),
        image: Some("image"),
        highlights: &["datePublished", "published_by"],
        body: Some("description"),
        mono: None,
        preview: &[],
        also: &["creative_work", "product"],
        icon: Some("book"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("booking_offer", Display {
        title: None,
        subtitle: Some("totalAmount"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("receipt"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("bookmark", Display {
        title: None,
        subtitle: Some("name"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("bookmark"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("branch", Display {
        title: None,
        subtitle: Some("commit"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("account_tree"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("brand", Display {
        title: None,
        subtitle: Some("tagline"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("badge"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("browser", Display {
        title: None,
        subtitle: Some("appName"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("public"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("calendar", Display {
        title: None,
        subtitle: Some("source"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("calendar_today"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("channel", Display {
        title: None,
        subtitle: Some("subscriberCount"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("subscriptions"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("class", Display {
        title: None,
        subtitle: Some("activityType"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("fitness_center"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("community", Display {
        title: None,
        subtitle: Some("text"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("groups"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("concern", Display {
        title: None,
        subtitle: Some("category"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("cardiology"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("conversation", Display {
        title: None,
        subtitle: Some("text"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[("content", PreviewPolicy::Full)],
        also: &[],
        icon: Some("forum"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("conversion", Display {
        title: None,
        subtitle: Some("kind"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("currency_exchange"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("creative_work", Display {
        title: None,
        subtitle: Some("written_by"),
        image: Some("image"),
        highlights: &["datePublished", "published_by"],
        body: Some("description"),
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("palette"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("cursor", Display {
        title: None,
        subtitle: Some("purpose"),
        image: Some("image"),
        highlights: &["datePublished", "published_by"],
        body: Some("description"),
        mono: None,
        preview: &[],
        also: &["creative_work", "file"],
        icon: Some("mouse"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("device", Display {
        title: None,
        subtitle: Some("ipAddress"),
        image: None,
        highlights: &["manufacturer", "vendor", "hostname", "roles", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["hardware", "product"],
        icon: Some("devices_other"),
        icon_from: Some("formFactor"),
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("dimension", Display {
        title: None,
        subtitle: Some("label"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("straighten"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("dns_record", Display {
        title: None,
        subtitle: Some("recordType"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("dns"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("document", Display {
        title: None,
        subtitle: Some("contentType"),
        image: None,
        highlights: &["datePublished", "author", "wordCount"],
        body: Some("abstract"),
        mono: None,
        preview: &[],
        also: &["file"],
        icon: Some("description"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("domain", Display {
        title: None,
        subtitle: Some("registrar"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("language"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("email", Display {
        title: None,
        subtitle: Some("author"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[("content", PreviewPolicy::Full)],
        also: &["message"],
        icon: Some("mail"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("episode", Display {
        title: None,
        subtitle: Some("author"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("podcasts"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("event", Display {
        title: None,
        subtitle: Some("startDate"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("event"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("fare", Display {
        title: None,
        subtitle: Some("fareFamily"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("airline_seat_recline_normal"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("file", Display {
        title: None,
        subtitle: Some("path"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("draft"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("financial_account", Display {
        title: None,
        subtitle: Some("last4"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("account_balance"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("flight", Display {
        title: None,
        subtitle: Some("airline"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["leg", "event"],
        icon: Some("flight_class"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("font", Display {
        title: None,
        subtitle: Some("author"),
        image: Some("image"),
        highlights: &["datePublished", "published_by"],
        body: Some("description"),
        mono: None,
        preview: &[],
        also: &["creative_work"],
        icon: Some("text_fields"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("git_commit", Display {
        title: None,
        subtitle: Some("author"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("commit"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("group", Display {
        title: None,
        subtitle: Some("category"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("group"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("hardware", Display {
        title: None,
        subtitle: Some("modelNumber"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &["product"],
        icon: Some("memory"),
        icon_from: Some("formFactor"),
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("health-biomarker", Display {
        title: None,
        subtitle: Some("category"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("glucose"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("health-condition", Display {
        title: None,
        subtitle: Some("clinicalStatus"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("sick"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("health-immunization", Display {
        title: None,
        subtitle: Some("dateAdministered"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("vaccines"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("health-lab", Display {
        title: None,
        subtitle: Some("labType"),
        image: Some("image"),
        highlights: &["headquarters"],
        body: None,
        mono: None,
        preview: &[],
        also: &["organization", "actor"],
        icon: Some("biotech"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("health-panel", Display {
        title: None,
        subtitle: Some("collectedAt"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &["list"],
        icon: Some("lab_panel"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("health-procedure", Display {
        title: None,
        subtitle: Some("performedDate"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("surgical"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("health-reference-range", Display {
        title: None,
        subtitle: Some("refText"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("straighten"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("icon", Display {
        title: None,
        subtitle: Some("purpose"),
        image: Some("image"),
        highlights: &["datePublished", "published_by"],
        body: Some("description"),
        mono: None,
        preview: &[],
        also: &["creative_work"],
        icon: Some("glyphs"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("image", Display {
        title: None,
        subtitle: Some("format"),
        image: Some("image"),
        highlights: &["datePublished", "published_by"],
        body: Some("description"),
        mono: None,
        preview: &[],
        also: &["creative_work", "file"],
        icon: Some("image"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("insurance_coverage", Display {
        title: None,
        subtitle: Some("limit"),
        image: None,
        highlights: &["limit", "requiresPreauth", "requiresReferral", "deductible"],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("health_and_safety"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("insurance_policy", Display {
        title: None,
        subtitle: Some("coverageType"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["membership", "event"],
        icon: Some("shield"),
        icon_from: None,
        labels: &[("price", "premium")],
        media: None,
        lines: &[],
    }),
    ("intellectual_property", Display {
        title: None,
        subtitle: Some("category"),
        image: None,
        highlights: &["identifier", "status", "granted_by"],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("copyright"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("invitation", Display {
        title: None,
        subtitle: Some("invitationType"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("forward_to_inbox"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("issue", Display {
        title: None,
        subtitle: Some("status"),
        image: None,
        highlights: &["status", "weight"],
        body: None,
        mono: None,
        preview: &[],
        also: &["post"],
        icon: Some("feedback"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("launch", Display {
        title: None,
        subtitle: Some("rocketId"),
        image: None,
        highlights: &["startDate", "rocketId", "launchpadId"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("rocket_launch"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("leg", Display {
        title: None,
        subtitle: Some("flightNumber"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("transfer_within_a_station"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("list", Display {
        title: None,
        subtitle: Some("name"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("folder"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("loaded_model", Display {
        title: None,
        subtitle: Some("size"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("memory"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("mcp_session", Display {
        title: None,
        subtitle: Some("client"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("terminal"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("measure", Display {
        title: None,
        subtitle: Some("at"),
        image: None,
        highlights: &["value", "flag"],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("vital_signs"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("meeting", Display {
        title: None,
        subtitle: Some("location"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("video_call"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("membership", Display {
        title: None,
        subtitle: Some("status"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("card_membership"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("message", Display {
        title: None,
        subtitle: Some("from"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[("content", PreviewPolicy::Full)],
        also: &[],
        icon: Some("chat"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("model", Display {
        title: None,
        subtitle: Some("name"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("psychology"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("module", Display {
        title: None,
        subtitle: Some("role"),
        image: None,
        highlights: &["status", "path"],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("extension"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("network", Display {
        title: None,
        subtitle: Some("ssid"),
        image: None,
        highlights: &["ssid", "subnet"],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("wifi"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("note", Display {
        title: None,
        subtitle: Some("noteType"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("sticky_note_2"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("offer", Display {
        title: None,
        subtitle: Some("price"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("sell"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("order", Display {
        title: None,
        subtitle: Some("total"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("shopping_cart"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("organization", Display {
        title: None,
        subtitle: Some("industry"),
        image: Some("image"),
        highlights: &["headquarters"],
        body: None,
        mono: None,
        preview: &[],
        also: &["actor"],
        icon: Some("apartment"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("outcome", Display {
        title: None,
        subtitle: Some("status"),
        image: None,
        highlights: &["status", "priority"],
        body: Some("statement"),
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("flag"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("pass", Display {
        title: None,
        subtitle: Some("status"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("confirmation_number"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("payment_method", Display {
        title: None,
        subtitle: Some("displayName"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("credit_card"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("person", Display {
        title: None,
        subtitle: Some("about"),
        image: Some("image"),
        highlights: &["birthDate", "gender"],
        body: Some("notes"),
        mono: None,
        preview: &[],
        also: &["actor"],
        icon: Some("person"),
        icon_from: None,
        labels: &[],
        media: Some(Media { field: "image", shape: Some("circle"), size: None }),
        lines: &["jobTitle", "current_residence"],
    }),
    ("persona", Display {
        title: None,
        subtitle: Some("headline"),
        image: None,
        highlights: &["reachesFor", "quote"],
        body: Some("who"),
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("face"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("place", Display {
        title: None,
        subtitle: Some("featureType"),
        image: Some("image"),
        highlights: &["city", "country", "rating"],
        body: Some("fullAddress"),
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("location_on"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("platform", Display {
        title: None,
        subtitle: Some("category"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &["product"],
        icon: Some("hub"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("playlist", Display {
        title: None,
        subtitle: Some("text"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &["list"],
        icon: Some("queue_music"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("plugin", Display {
        title: None,
        subtitle: Some("description"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("cable"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("podcast", Display {
        title: None,
        subtitle: Some("host"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("podcasts"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("post", Display {
        title: None,
        subtitle: Some("author"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("newspaper"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("practice", Display {
        title: None,
        subtitle: Some("parent"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("sports_gymnastics"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("principle", Display {
        title: None,
        subtitle: Some("domain"),
        image: None,
        highlights: &["statement", "status"],
        body: Some("rationale"),
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("gavel"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("product", Display {
        title: None,
        subtitle: Some("brand"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("inventory_2"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("project", Display {
        title: None,
        subtitle: Some("state"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("view_kanban"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("protocol", Display {
        title: None,
        subtitle: Some("name"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("handshake"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("qualification", Display {
        title: None,
        subtitle: Some("category"),
        image: None,
        highlights: &["identifier", "validIn", "granted_by"],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("workspace_premium"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("quantity-kind", Display {
        title: None,
        subtitle: Some("label"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("functions"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("quote", Display {
        title: None,
        subtitle: Some("year"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("format_quote"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("repository", Display {
        title: None,
        subtitle: Some("language"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("source_notes"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("reservation", Display {
        title: None,
        subtitle: Some("reservationType"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("event_available"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("result", Display {
        title: None,
        subtitle: Some("url"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("manage_search"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("review", Display {
        title: None,
        subtitle: Some("author"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &["post"],
        icon: Some("star_rate"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("role", Display {
        title: None,
        subtitle: Some("name"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("work"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("seatmap", Display {
        title: Some("flightNumber"),
        subtitle: None,
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("event_seat"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("service", Display {
        title: None,
        subtitle: Some("description"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("hub"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("settings", Display {
        title: None,
        subtitle: Some("name"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("tune"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("shape", Display {
        title: None,
        subtitle: Some("description"),
        image: None,
        highlights: &["plural"],
        body: Some("description"),
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("category"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("shelf", Display {
        title: None,
        subtitle: Some("isExclusive"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &["list"],
        icon: Some("shelves"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("software", Display {
        title: None,
        subtitle: Some("applicationCategory"),
        image: None,
        highlights: &["version", "runtimePlatform"],
        body: None,
        mono: None,
        preview: &[],
        also: &["product"],
        icon: Some("apps"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("sound", Display {
        title: None,
        subtitle: Some("purpose"),
        image: Some("image"),
        highlights: &["datePublished", "published_by"],
        body: Some("description"),
        mono: None,
        preview: &[],
        also: &["creative_work", "file"],
        icon: Some("music_note"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("source", Display {
        title: None,
        subtitle: Some("sourceId"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("folder_open"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("spec", Display {
        title: None,
        subtitle: Some("state"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["task", "event", "file"],
        icon: Some("fact_check"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("subscription", Display {
        title: None,
        subtitle: Some("target"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("notifications_active"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("symbol", Display {
        title: None,
        subtitle: Some("signature"),
        image: None,
        highlights: &["kind", "lang", "sourcePath"],
        body: Some("summary"),
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("code"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("tag", Display {
        title: Some("name"),
        subtitle: Some("tagType"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("label"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("task", Display {
        title: None,
        subtitle: Some("state"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("task_alt"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("tax_line", Display {
        title: None,
        subtitle: Some("description"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("percent"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("theme", Display {
        title: None,
        subtitle: None,
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("palette"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("tool_call", Display {
        title: None,
        subtitle: Some("name"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("build"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("transaction", Display {
        title: None,
        subtitle: Some("category"),
        image: None,
        highlights: &["amount", "postingDate", "currency"],
        body: Some("notes"),
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("receipt_long"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("transcript", Display {
        title: None,
        subtitle: Some("language"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("closed_caption"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("treatment", Display {
        title: None,
        subtitle: Some("abbreviation"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("healing"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("trip", Display {
        title: None,
        subtitle: Some("tripType"),
        image: None,
        highlights: &["startDate", "endDate", "location"],
        body: None,
        mono: None,
        preview: &[],
        also: &["event"],
        icon: Some("trip"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("unit", Display {
        title: None,
        subtitle: Some("symbol"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("straighten"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("user", Display {
        title: None,
        subtitle: Some("name"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &["actor"],
        icon: Some("account_circle"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("user_identity", Display {
        title: None,
        subtitle: Some("volume_id"),
        image: None,
        highlights: &["person_node_id", "active"],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("fingerprint"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("video", Display {
        title: None,
        subtitle: Some("author"),
        image: Some("image"),
        highlights: &["datePublished", "published_by"],
        body: Some("description"),
        mono: None,
        preview: &[],
        also: &["creative_work", "file"],
        icon: Some("movie"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("volume", Display {
        title: None,
        subtitle: Some("kind"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("hard_drive"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("vote", Display {
        title: None,
        subtitle: Some("direction"),
        image: None,
        highlights: &[],
        body: Some("note"),
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("thumb_up"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
    ("website", Display {
        title: None,
        subtitle: Some("url"),
        image: None,
        highlights: &[],
        body: None,
        mono: None,
        preview: &[],
        also: &[],
        icon: Some("public"),
        icon_from: None,
        labels: &[],
        media: None,
        lines: &[],
    }),
];

// ===========================================================
// Field order — YAML declaration order per shape
// ===========================================================

pub fn lookup_field_order(shape: &str) -> &'static [&'static str] {
    SHAPE_FIELD_ORDER.iter().find(|(name, _)| *name == shape).map(|(_, o)| *o).unwrap_or(&[])
}

pub static SHAPE_FIELD_ORDER: &[(&'static str, &'static [&'static str])] = &[
    ("account", &["identifier", "handle", "displayName", "display", "email", "phone", "bio", "accountType", "color", "isActive", "joinedDate", "lastActive", "lastProfileFetch", "userId", "issuer", "metadata"]),
    ("activity", &["action", "changedKeys", "toolName", "duration", "success", "startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("actor", &["actorType"]),
    ("aircraft", &["model", "variant", "seatCapacity", "rangeKm", "iataCode", "icaoCode", "category", "price", "priceAmount", "originalPrice", "originalPriceAmount", "currency", "categories", "availability", "images", "quantity", "weight", "weightValue", "weightUnit", "soldByWeight", "department", "aisle", "sku", "barcode", "nutritionScore", "novaGroup", "calories", "servingSize", "customizationGroups"]),
    ("airline", &["iataCode", "icaoCode", "callsign", "country", "alliance", "industry", "actorType"]),
    ("airport", &["iataCode", "icaoCode", "city", "country", "countryCode", "timezone", "elevationFt", "terminalCount"]),
    ("app", &["id", "name", "description", "color", "iconRole", "route", "defaultRoute", "defaultView", "isSystem", "handles", "composition", "layout", "account"]),
    ("auth_challenge", &["kind", "payload", "artifact", "instructions", "retrieval", "expiresAt", "continueWith"]),
    ("book", &["isbn", "isbn13", "pages", "genres", "series", "format", "language", "originalTitle", "places", "characters", "awardsWon", "name", "description", "license", "copyrightYear", "datePublished", "dateCreated", "url", "coverage", "tags", "category", "price", "priceAmount", "originalPrice", "originalPriceAmount", "currency", "categories", "availability", "images", "quantity", "weight", "weightValue", "weightUnit", "soldByWeight", "department", "aisle", "sku", "barcode", "nutritionScore", "novaGroup", "calories", "servingSize", "customizationGroups"]),
    ("booking_offer", &["cartId", "referenceNumber", "status", "preparedAt", "presentedAt", "approvedAt", "expiresAt", "currency", "baseAmount", "taxAmount", "feesAmount", "totalAmount", "itineraryHash", "signature", "signatureAlg", "signedBy", "checkoutUrl", "confirmEndpoint", "isRefundable", "isChangeable", "hasVoidWindow", "voidWindowEndsAt", "conditions", "blob", "review", "contactEmail", "contactPhone", "startDate", "endDate", "timezone", "allDay", "recurrence", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("bookmark", &["name", "handle", "address"]),
    ("branch", &["commit", "upstream", "ahead", "behind", "isCurrent", "isRemote"]),
    ("brand", &["tagline", "country", "primaryColor", "textColor"]),
    ("browser", &["id", "name", "appName", "installed", "macosDefault"]),
    ("calendar", &["calendarId", "color", "backgroundColor", "foregroundColor", "isPrimary", "isReadonly", "accessRole", "source", "timezone"]),
    ("channel", &["banner", "subscriberCount"]),
    ("class", &["activityType", "capacity", "spotsRemaining", "isFull", "startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("community", &["privacy", "memberCount", "subscriberCount", "allowCrypto"]),
    ("concern", &["category", "status", "intensity", "startDate", "endDate", "timezone", "allDay", "recurrence", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("conversation", &["isGroup", "isArchived", "unreadCount", "messageCount", "accountEmail", "historyId", "source", "cwd", "gitBranch"]),
    ("conversion", &["kind", "factor", "rate", "startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("creative_work", &["name", "description", "license", "copyrightYear", "datePublished", "dateCreated", "url", "language", "coverage", "tags"]),
    ("cursor", &["hotspotX", "hotspotY", "dimension", "format", "purpose", "name", "description", "license", "copyrightYear", "datePublished", "dateCreated", "url", "language", "coverage", "tags", "filename", "mimeType", "size", "path", "encoding", "lineCount", "kind", "sha"]),
    ("device", &["macAddress", "ipAddress", "ipv6", "hostname", "vendor", "location", "roles", "openPorts", "online", "macRandomized", "discoveredVia", "lastSeen", "manufacturer", "model", "modelNumber", "formFactor", "category", "price", "priceAmount", "originalPrice", "originalPriceAmount", "currency", "categories", "availability", "images", "quantity", "weight", "weightValue", "weightUnit", "soldByWeight", "department", "aisle", "sku", "barcode", "nutritionScore", "novaGroup", "calories", "servingSize", "customizationGroups"]),
    ("dimension", &["key", "label", "length", "mass", "time", "current", "temperature", "amount", "luminous", "dimensionless"]),
    ("dns_record", &["domain", "recordName", "recordType", "type", "ttl", "priority", "recordId", "values"]),
    ("document", &["contentType", "fidelity", "url", "language", "wordCount", "abstract", "tableOfContents", "filename", "mimeType", "size", "path", "format", "encoding", "lineCount", "kind", "sha"]),
    ("domain", &["status", "registrar", "autoRenew", "nameservers"]),
    ("email", &["subject", "messageId", "inReplyTo", "isUnread", "isStarred", "isDraft", "isSent", "isTrash", "isSpam", "isInbox", "hasAttachments", "draftId", "conversationId", "accountEmail", "sizeEstimate", "references", "replyTo", "deliveredTo", "attachments", "toRaw", "ccRaw", "bccRaw", "unsubscribe", "unsubscribeOneClick", "manageSubscription", "listId", "isAutomated", "precedence", "mailer", "returnPath", "authResults", "isOutgoing"]),
    ("episode", &["durationMs", "episodeNumber", "seasonNumber"]),
    ("event", &["startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("fare", &["identifier", "bookingCode", "productType", "fareFamily", "class", "basePrice", "currency", "passengerType", "milesEarned", "pointsEarned", "components", "refundable", "changeable", "restrictions", "conditions"]),
    ("file", &["filename", "mimeType", "size", "path", "format", "encoding", "lineCount", "kind", "sha"]),
    ("financial_account", &["identifier", "accountId", "accountNumber", "routingNumber", "last4", "currency", "accountType", "balance", "available", "creditLimit", "minimumPayment", "cardType", "interestRate"]),
    ("flight", &["flightNumber", "durationMinutes", "cabinClass", "stops", "carbonEmissions", "sequence", "departureTime", "arrivalTime", "duration", "vehicleType", "layoverMinutes", "trace", "tracePointCount", "polyline", "startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("font", &["family", "genericFamily", "postscriptName", "weights", "styles", "formats", "scripts", "glyphCount", "designerUrl", "vendorUrl", "licenseInfoUrl", "name", "description", "license", "copyrightYear", "datePublished", "dateCreated", "url", "language", "coverage", "tags"]),
    ("git_commit", &["sha", "shortHash", "message", "additions", "deletions", "filesChanged", "committedAt", "startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("group", &["memberCount", "category"]),
    ("hardware", &["manufacturer", "model", "modelNumber", "formFactor", "category", "price", "priceAmount", "originalPrice", "originalPriceAmount", "currency", "categories", "availability", "images", "quantity", "weight", "weightValue", "weightUnit", "soldByWeight", "department", "aisle", "sku", "barcode", "nutritionScore", "novaGroup", "calories", "servingSize", "customizationGroups"]),
    ("health-biomarker", &["measure", "category", "loincCode", "analyteType", "description"]),
    ("health-condition", &["clinicalStatus", "verificationStatus", "bodySite", "severity", "snomedCode", "icd10Code", "clinicalArea", "mitigation", "startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("health-immunization", &["dateAdministered", "cvxCode", "manufacturer", "lotNumber", "doseNumber", "seriesDoses", "site", "route", "diseaseTarget", "notes", "startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("health-lab", &["cliaNumber", "npi", "ccn", "labType", "accreditation", "industry", "actorType"]),
    ("health-panel", &["panelCode", "fasting", "description", "collectedAt", "orderedAt", "receivedAt", "reportedAt", "verifiedAt", "id", "listId", "listType", "ordering_mode", "member_shape", "privacy", "isDefault", "isPublic", "itemCount", "arrangement", "default_view", "icon_size", "sort_by", "path"]),
    ("health-procedure", &["performedDate", "procedureType", "bodySite", "outcome", "status", "cptCode", "snomedCode", "findings", "followUp", "startDate", "endDate", "timezone", "allDay", "recurrence", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("health-reference-range", &["low", "high", "unit", "refText", "category", "provenance", "method", "ageLow", "ageHigh", "sex", "pregnancy", "gestationalAge", "fasting", "timeOfDay", "startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("icon", &["dimension", "format", "url", "component", "purpose", "style", "name", "description", "license", "copyrightYear", "datePublished", "dateCreated", "language", "coverage", "tags"]),
    ("image", &["width", "height", "format", "altText", "appName", "windowId", "displayId", "displayIndex", "name", "description", "license", "copyrightYear", "datePublished", "dateCreated", "url", "language", "coverage", "tags", "filename", "mimeType", "size", "path", "encoding", "lineCount", "kind", "sha"]),
    ("insurance_coverage", &["limit", "limitBasis", "deductible", "outOfPocketMax", "copay", "coinsurance", "currency", "requiresPreauth", "requiresReferral", "waitingPeriodMonths", "notes"]),
    ("insurance_policy", &["coverageType", "policyNumber", "memberId", "groupNumber", "network", "status", "tier", "autoRenew", "price", "currency", "billingType", "useCount", "guestPassQuantity", "startDate", "endDate", "timezone", "allDay", "recurrence", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("intellectual_property", &["category", "mark", "identifier", "register", "status", "filingBasis", "niceClass", "validIn", "renewalPeriod", "verificationUrl"]),
    ("invitation", &["invitationType", "email", "role", "status", "token", "acceptedAt", "revokedAt", "message", "startDate", "endDate", "timezone", "allDay", "recurrence", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("issue", &["declined", "externalUrl", "postType", "score", "commentCount", "community"]),
    ("launch", &["flightNumber", "rocketId", "launchpadId", "crewIds", "reusedBoosters", "landingOutcomes", "articleUrl", "webcastUrl", "wikipediaUrl", "patchImage", "startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("leg", &["sequence", "departureTime", "arrivalTime", "duration", "durationMinutes", "flightNumber", "cabinClass", "vehicleType", "layoverMinutes", "carbonEmissions", "trace", "tracePointCount", "polyline", "startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("list", &["id", "listId", "listType", "ordering_mode", "member_shape", "privacy", "isDefault", "isPublic", "itemCount", "arrangement", "default_view", "icon_size", "sort_by", "path"]),
    ("loaded_model", &["size", "quantization", "vramUsage", "sizeVram", "digest", "startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("mcp_session", &["client", "projectId", "gitBranch", "sessionType", "startedAt", "endedAt", "messageCount", "tokenCount"]),
    ("measure", &["at", "start", "end", "value", "valueText", "refLow", "refHigh", "refText", "flag", "status", "method", "notes"]),
    ("meeting", &["calendarLink", "isVirtual", "meetingUrl", "conferenceProvider", "phoneDialIn", "meetingType", "startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("membership", &["status", "tier", "autoRenew", "price", "currency", "billingType", "useCount", "guestPassQuantity", "startDate", "endDate", "timezone", "allDay", "recurrence", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("message", &["isOutgoing", "isStarred", "conversationId", "accountEmail"]),
    ("model", &["contextLength", "contextWindow", "maxOutput", "pricingInput", "pricingOutput", "modality", "modelType", "quantization", "quantizationLevel", "size", "parameterSize", "format", "family", "digest"]),
    ("module", &["name", "role", "path", "version", "status", "planned"]),
    ("network", &["ssid", "bssid", "gatewayIp", "gatewayMac", "subnet", "lastSeen"]),
    ("note", &["noteType", "isPinned"]),
    ("offer", &["price", "currency", "offerType", "availability", "bookingToken", "departureToken", "startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("order", &["orderId", "orderDate", "total", "totalAmount", "originalTotal", "originalTotalAmount", "savings", "currency", "status", "deliveryDate", "eta", "subtotal", "tipAmount", "deliveryFee", "taxes", "summary", "fareBreakdown", "deliveryInstructions", "interactionType", "orderUuid", "body", "head", "messages", "timeline", "itemStates", "latestArrival", "progress", "progressTotal", "startDate", "endDate", "timezone", "allDay", "recurrence", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("organization", &["industry", "actorType"]),
    ("outcome", &["statement", "status", "priority", "archived", "metric", "baseline", "current", "target"]),
    ("pass", &["status", "quantity", "purchasedQuantity", "useCount", "isAllDayPass", "price", "currency", "ticketNumber", "nameOnTicket", "seatAssignment", "boardingGroup", "ticketClass", "gate", "terminal", "checkinStatus", "startDate", "endDate", "timezone", "allDay", "recurrence", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("payment_method", &["identifier", "type", "subtype", "brand", "displayName", "customDescription", "holderName", "last4", "binRange", "expMonth", "expYear", "expirationDate", "currency", "balance", "fingerprint", "isDefault", "isPrimary", "isExpired", "isSelected", "status", "providerTokens", "metadata"]),
    ("person", &["url", "notes", "about", "givenName", "additionalName", "familyName", "honorificPrefix", "honorificSuffix", "legalName", "maidenName", "sortAs", "nameOrder", "phoneticGivenName", "phoneticFamilyName", "nickname", "gender", "jobTitle", "birthDate", "deathDate", "identities", "actorType"]),
    ("persona", &["headline", "who", "goals", "painPoints", "reachesFor", "quote"]),
    ("place", &["fullAddress", "placeFormatted", "streetNumber", "street", "neighborhood", "locality", "city", "district", "region", "postalCode", "country", "countryCode", "latitude", "longitude", "accuracy", "featureType", "categories", "phone", "website", "hours", "businessStatus", "rating", "reviewCount", "priceLevel", "timezone", "eta", "isOrderable", "closedMessage", "productCount", "mapboxId", "wikidataId", "googlePlaceId"]),
    ("platform", &["slug", "federated", "protocol", "urlTemplate", "category", "price", "priceAmount", "originalPrice", "originalPriceAmount", "currency", "categories", "availability", "images", "quantity", "weight", "weightValue", "weightUnit", "soldByWeight", "department", "aisle", "sku", "barcode", "nutritionScore", "novaGroup", "calories", "servingSize", "customizationGroups"]),
    ("playlist", &["id", "listId", "listType", "ordering_mode", "member_shape", "privacy", "isDefault", "isPublic", "itemCount", "arrangement", "default_view", "icon_size", "sort_by", "path"]),
    ("plugin", &["id", "name", "description", "color", "status", "error", "iconRole", "handles", "composition", "account"]),
    ("podcast", &["feedUrl"]),
    ("post", &["externalUrl", "postType", "score", "commentCount", "community"]),
    ("practice", &["description", "code", "codeSystem", "aliases"]),
    ("principle", &["name", "statement", "rationale", "domain", "status"]),
    ("product", &["category", "price", "priceAmount", "originalPrice", "originalPriceAmount", "currency", "categories", "availability", "images", "quantity", "weight", "weightValue", "weightUnit", "soldByWeight", "department", "aisle", "sku", "barcode", "nutritionScore", "novaGroup", "calories", "servingSize", "customizationGroups"]),
    ("project", &["state", "color", "parentId"]),
    ("protocol", &["name", "homepage", "rfc", "wikidataId"]),
    ("qualification", &["category", "identifier", "status", "renewalPeriod", "level", "validIn", "verificationUrl"]),
    ("quantity-kind", &["key", "label"]),
    ("quote", &["context", "year"]),
    ("repository", &["stars", "forks", "language", "topics", "openIssues", "isArchived", "isPrivate", "defaultBranch", "license", "size"]),
    ("reservation", &["reservationType", "reservationId", "status", "bookingType", "bookingTime", "modifiedTime", "startTime", "endTime", "partySize", "totalAmount", "baseAmount", "taxAmount", "currency", "checkinUrl", "conditions", "voidWindowEndsAt", "availableActions", "startDate", "endDate", "timezone", "allDay", "recurrence", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("result", &["indexedAt", "resultType", "favicon", "externalUrl", "postId", "score", "similarity", "community"]),
    ("review", &["rating", "ratingMax", "tags", "isVerified", "externalUrl", "postType", "score", "commentCount", "community"]),
    ("role", &["title", "department", "roleType", "startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("seatmap", &["flightNumber", "origin", "destination", "fareBasisCode", "classOfService", "aircraftCode", "totalSeats", "availableSeats", "cabins", "tiers", "hasExitRow", "hasFreeSeats", "hasPaidSeats", "basicEconomyLocked"]),
    ("service", &["id", "description"]),
    ("settings", &["name"]),
    ("shape", &["plural", "description", "icon", "fields", "out", "in", "display", "groups", "identity", "identity_any", "also", "derived", "shortcuts", "prior_art", "prefsSchemas"]),
    ("shelf", &["isExclusive", "id", "listId", "listType", "ordering_mode", "member_shape", "privacy", "isDefault", "isPublic", "itemCount", "arrangement", "default_view", "icon_size", "sort_by", "path"]),
    ("software", &["version", "applicationCategory", "runtimePlatform", "codename", "category", "price", "priceAmount", "originalPrice", "originalPriceAmount", "currency", "categories", "availability", "images", "quantity", "weight", "weightValue", "weightUnit", "soldByWeight", "department", "aisle", "sku", "barcode", "nutritionScore", "novaGroup", "calories", "servingSize", "customizationGroups"]),
    ("sound", &["durationMs", "channels", "sampleRate", "bitDepth", "purpose", "name", "description", "license", "copyrightYear", "datePublished", "dateCreated", "url", "language", "coverage", "tags", "filename", "mimeType", "size", "path", "format", "encoding", "lineCount", "kind", "sha"]),
    ("source", &["sourceId", "address", "scanner", "enabled", "description", "lastSynced"]),
    ("spec", &["problem", "successCriteria", "remoteId", "priority", "state", "labels", "targetDate", "target", "parentId", "projectId", "startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties", "filename", "mimeType", "size", "path", "format", "encoding", "lineCount", "kind", "sha"]),
    ("subscription", &["app", "op", "target"]),
    ("symbol", &["urn", "kind", "lang", "signature", "summary", "sourcePath", "sourceLine"]),
    ("tag", &["color", "tagType", "annotated", "hash"]),
    ("task", &["remoteId", "priority", "state", "labels", "targetDate", "target", "parentId", "projectId", "startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("tax_line", &["code", "description", "amount", "currency", "kind", "nature", "country", "appliesToIndex", "refundable", "merchantImposed", "rate", "taxableAmount", "inclusive"]),
    ("theme", &["themeId", "description", "defaultBackgroundColor"]),
    ("tool_call", &["name", "input", "output", "isError", "durationMs"]),
    ("transaction", &["amount", "currency", "balance", "category", "postingDate", "pending", "recurring", "notes", "type", "details", "startDate", "endDate", "timezone", "allDay", "recurrence", "status", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("transcript", &["language", "languageConfidence", "sourceType", "contentRole", "durationMs", "segmentCount", "segments"]),
    ("treatment", &["abbreviation", "description", "aliases"]),
    ("trip", &["tripType", "status", "departureTime", "arrivalTime", "duration", "durationMinutes", "distance", "vehicleType", "cabinClass", "fare", "fareAmount", "currency", "rating", "trackingUrl", "isSurge", "isScheduled", "stops", "bookingToken", "carbonEmissions", "isPool", "isReserve", "guest", "marketplace", "vehicle", "startDate", "endDate", "timezone", "allDay", "recurrence", "visibility", "showAs", "dateUpdated", "sourceUrl", "sourceTitle", "icalUid", "distinctId", "currentUrl", "properties"]),
    ("unit", &["ucumCode", "symbol", "label", "kind", "siDigitalFrameworkUri", "unCefactCommonCode", "qudtUnitIri", "wikidataId", "toBaseFactor", "toBaseOffset", "iso4217", "iso4217Numeric", "minorExponent", "logBase"]),
    ("user", &["osUsername", "primaryUser", "actorType"]),
    ("user_identity", &["user_id", "volume_id", "person_node_id", "active"]),
    ("video", &["durationMs", "resolution", "frameRate", "codec", "viewCount", "name", "description", "license", "copyrightYear", "datePublished", "dateCreated", "url", "language", "coverage", "tags", "filename", "mimeType", "size", "path", "format", "encoding", "lineCount", "kind", "sha"]),
    ("volume", &["volume_id", "kind", "source", "address", "provider", "auto_mount", "readOnly", "removable", "ejectable", "totalBytes", "freeBytes", "scope", "icon", "default_view"]),
    ("vote", &["direction", "note", "instance"]),
    ("website", &["status", "versionId", "anonymous", "claimToken", "claimUrl"]),
];

// ===========================================================
// Identity — the `identity:` field list per shape
// ===========================================================

pub fn lookup_identity(shape: &str) -> &'static [&'static str] {
    SHAPE_IDENTITY.iter().find(|(name, _)| *name == shape).map(|(_, i)| *i).unwrap_or(&[])
}

pub static SHAPE_IDENTITY: &[(&'static str, &'static [&'static str])] = &[
    ("account", &["at", "identifier"]),
    ("aircraft", &["icaoCode"]),
    ("airline", &["iataCode"]),
    ("airport", &["iataCode"]),
    ("app", &["id"]),
    ("book", &["isbn13", "isbn"]),
    ("booking_offer", &["at", "cartId"]),
    ("bookmark", &["points_to"]),
    ("brand", &["url"]),
    ("browser", &["id"]),
    ("calendar", &["at", "calendarId"]),
    ("channel", &["at", "id"]),
    ("community", &["at", "id"]),
    ("concern", &["name"]),
    ("conversation", &["at", "id"]),
    ("cursor", &["sha", "url"]),
    ("device", &["macAddress"]),
    ("dimension", &["key"]),
    ("dns_record", &["domain", "recordType", "recordName"]),
    ("document", &["sha", "url"]),
    ("domain", &["name"]),
    ("email", &["at", "id"]),
    ("event", &["at", "id"]),
    ("fare", &["at", "identifier"]),
    ("file", &["sha", "url"]),
    ("financial_account", &["at", "identifier"]),
    ("font", &["family", "postscriptName"]),
    ("group", &["at", "id"]),
    ("hardware", &["url", "modelNumber"]),
    ("health-biomarker", &["loincCode", "measure"]),
    ("health-condition", &["snomedCode", "name"]),
    ("health-lab", &["cliaNumber", "url"]),
    ("health-procedure", &["cptCode", "snomedCode", "id"]),
    ("health-reference-range", &["analyte", "issuingLab", "method", "startDate"]),
    ("icon", &["component", "url"]),
    ("image", &["sha", "url"]),
    ("insurance_policy", &["underwritten_by", "policyNumber"]),
    ("intellectual_property", &["identifier"]),
    ("invitation", &["at", "id"]),
    ("list", &["at", "id"]),
    ("mcp_session", &["client", "projectId", "gitBranch"]),
    ("membership", &["at", "id"]),
    ("message", &["at", "id"]),
    ("model", &["at", "name"]),
    ("network", &["gatewayMac"]),
    ("offer", &["id"]),
    ("order", &["at", "orderId"]),
    ("organization", &["name"]),
    ("pass", &["at", "id"]),
    ("payment_method", &["at", "identifier"]),
    ("place", &["googlePlaceId", "mapboxId"]),
    ("platform", &["slug"]),
    ("plugin", &["id"]),
    ("podcast", &["at", "id"]),
    ("post", &["at", "id"]),
    ("product", &["url"]),
    ("project", &["at", "id"]),
    ("protocol", &["name"]),
    ("qualification", &["identifier"]),
    ("quantity-kind", &["key"]),
    ("repository", &["path", "url"]),
    ("reservation", &["at", "reservationId"]),
    ("seatmap", &["id"]),
    ("service", &["id"]),
    ("shape", &["name"]),
    ("software", &["url"]),
    ("sound", &["sha", "url"]),
    ("source", &["address"]),
    ("subscription", &["app", "op"]),
    ("tag", &["name"]),
    ("task", &["at", "id"]),
    ("tax_line", &["at", "id"]),
    ("theme", &["themeId"]),
    ("tool_call", &["platform", "id"]),
    ("transaction", &["at", "id"]),
    ("treatment", &["name", "abbreviation"]),
    ("trip", &["at", "id"]),
    ("unit", &["ucumCode", "siDigitalFrameworkUri", "iso4217"]),
    ("user", &["osUsername"]),
    ("video", &["sha", "url"]),
    ("website", &["url"]),
];

// ===========================================================
// Plurals — the ontology's `plural:` per shape
// ===========================================================

pub fn lookup_plural(shape: &str) -> Option<&'static str> {
    SHAPE_PLURALS.iter().find(|(name, _)| *name == shape).map(|(_, p)| *p)
}

pub static SHAPE_PLURALS: &[(&'static str, &'static str)] = &[
    ("account", "accounts"),
    ("activity", "activities"),
    ("actor", "actors"),
    ("aircraft", "aircraft"),
    ("airline", "airlines"),
    ("airport", "airports"),
    ("app", "apps"),
    ("auth_challenge", "auth_challenges"),
    ("book", "books"),
    ("booking_offer", "booking_offers"),
    ("bookmark", "bookmarks"),
    ("branch", "branches"),
    ("brand", "brands"),
    ("browser", "browsers"),
    ("calendar", "calendars"),
    ("channel", "channels"),
    ("class", "classes"),
    ("community", "communities"),
    ("concern", "concerns"),
    ("conversation", "conversations"),
    ("conversion", "conversions"),
    ("creative_work", "creative_works"),
    ("cursor", "cursors"),
    ("device", "devices"),
    ("dimension", "dimensions"),
    ("dns_record", "dns_records"),
    ("document", "documents"),
    ("domain", "domains"),
    ("email", "emails"),
    ("episode", "episodes"),
    ("event", "events"),
    ("fare", "fares"),
    ("file", "files"),
    ("financial_account", "financial_accounts"),
    ("flight", "flights"),
    ("font", "fonts"),
    ("git_commit", "git_commits"),
    ("group", "groups"),
    ("hardware", "hardware"),
    ("health-biomarker", "health-biomarkers"),
    ("health-condition", "health-conditions"),
    ("health-immunization", "health-immunizations"),
    ("health-lab", "health-labs"),
    ("health-panel", "health-panels"),
    ("health-procedure", "health-procedures"),
    ("health-reference-range", "health-reference-ranges"),
    ("icon", "icons"),
    ("image", "images"),
    ("insurance_coverage", "insurance_coverages"),
    ("insurance_policy", "insurance_policies"),
    ("intellectual_property", "intellectual_properties"),
    ("invitation", "invitations"),
    ("issue", "issues"),
    ("launch", "launches"),
    ("leg", "legs"),
    ("list", "lists"),
    ("loaded_model", "loaded_models"),
    ("mcp_session", "mcp_sessions"),
    ("measure", "measures"),
    ("meeting", "meetings"),
    ("membership", "memberships"),
    ("message", "messages"),
    ("model", "models"),
    ("module", "modules"),
    ("network", "networks"),
    ("note", "notes"),
    ("offer", "offers"),
    ("order", "orders"),
    ("organization", "organizations"),
    ("outcome", "outcomes"),
    ("pass", "passes"),
    ("payment_method", "payment_methods"),
    ("person", "people"),
    ("persona", "personas"),
    ("place", "places"),
    ("platform", "platforms"),
    ("playlist", "playlists"),
    ("plugin", "plugins"),
    ("podcast", "podcasts"),
    ("post", "posts"),
    ("practice", "practices"),
    ("principle", "principles"),
    ("product", "products"),
    ("project", "projects"),
    ("protocol", "protocols"),
    ("qualification", "qualifications"),
    ("quantity-kind", "quantity-kinds"),
    ("quote", "quotes"),
    ("repository", "repositories"),
    ("reservation", "reservations"),
    ("result", "results"),
    ("review", "reviews"),
    ("role", "roles"),
    ("seatmap", "seatmaps"),
    ("service", "services"),
    ("settings", "settings"),
    ("shape", "shapes"),
    ("shelf", "shelves"),
    ("software", "software"),
    ("sound", "sounds"),
    ("source", "sources"),
    ("spec", "specs"),
    ("subscription", "subscriptions"),
    ("symbol", "symbols"),
    ("tag", "tags"),
    ("task", "tasks"),
    ("tax_line", "tax_lines"),
    ("theme", "themes"),
    ("tool_call", "tool_calls"),
    ("transaction", "transactions"),
    ("transcript", "transcripts"),
    ("treatment", "treatments"),
    ("trip", "trips"),
    ("unit", "units"),
    ("user", "users"),
    ("user_identity", "user_identities"),
    ("video", "videos"),
    ("volume", "volumes"),
    ("vote", "votes"),
    ("website", "websites"),
];

// ===========================================================
// Ancestors — transitive `also:` closure per shape
// ===========================================================

pub fn lookup_ancestors(shape: &str) -> &'static [&'static str] {
    SHAPE_ANCESTORS.iter().find(|(n, _)| *n == shape).map(|(_, a)| *a).unwrap_or(&[])
}

pub static SHAPE_ANCESTORS: &[(&'static str, &'static [&'static str])] = &[
    ("activity", &["event"]),
    ("aircraft", &["product"]),
    ("airline", &["organization", "actor"]),
    ("book", &["creative_work", "product"]),
    ("booking_offer", &["event"]),
    ("class", &["event"]),
    ("concern", &["event"]),
    ("conversion", &["event"]),
    ("cursor", &["creative_work", "file"]),
    ("device", &["hardware", "product"]),
    ("document", &["file"]),
    ("email", &["message"]),
    ("flight", &["leg", "event"]),
    ("font", &["creative_work"]),
    ("git_commit", &["event"]),
    ("hardware", &["product"]),
    ("health-condition", &["event"]),
    ("health-immunization", &["event"]),
    ("health-lab", &["organization", "actor"]),
    ("health-panel", &["list"]),
    ("health-procedure", &["event"]),
    ("health-reference-range", &["event"]),
    ("icon", &["creative_work"]),
    ("image", &["creative_work", "file"]),
    ("insurance_policy", &["membership", "event"]),
    ("invitation", &["event"]),
    ("issue", &["post"]),
    ("launch", &["event"]),
    ("leg", &["event"]),
    ("loaded_model", &["event"]),
    ("meeting", &["event"]),
    ("membership", &["event"]),
    ("offer", &["event"]),
    ("order", &["event"]),
    ("organization", &["actor"]),
    ("pass", &["event"]),
    ("person", &["actor"]),
    ("platform", &["product"]),
    ("playlist", &["list"]),
    ("reservation", &["event"]),
    ("review", &["post"]),
    ("role", &["event"]),
    ("shelf", &["list"]),
    ("software", &["product"]),
    ("sound", &["creative_work", "file"]),
    ("spec", &["task", "event", "file"]),
    ("task", &["event"]),
    ("transaction", &["event"]),
    ("trip", &["event"]),
    ("user", &["actor"]),
    ("video", &["creative_work", "file"]),
];

// ===========================================================
// Event types — shapes whose `also:` chain includes `event`
// ===========================================================

pub static EVENT_TYPES: &[&'static str] = &["activity", "booking_offer", "class", "concern", "conversion", "event", "flight", "git_commit", "health-condition", "health-immunization", "health-procedure", "health-reference-range", "insurance_policy", "invitation", "launch", "leg", "loaded_model", "meeting", "membership", "offer", "order", "pass", "reservation", "role", "spec", "task", "transaction", "trip"];

// ===========================================================
// Derived bindings — per-shape `derived:` block as JSON
// ===========================================================

pub static SHAPE_DERIVED_JSON: &str = r#"{"issue": {"upvotes": {"count": "for", "where": {"direction": "up"}}, "downvotes": {"count": "for", "where": {"direction": "down"}}, "weight": {"tally": "for", "by": "direction", "map": {"up": 1, "down": -1}}, "status": {"reverse": "addresses", "get": "status", "prefer": ["achieved", "active", "at-risk", "proposed"], "map": {"achieved": "addressed", "active": "in-progress", "at-risk": "in-progress", "proposed": "planned"}, "default": "open", "authored": {"field": "declined", "equals": true, "then": "declined"}}}, "person": {"current_residence": {"find": "lived_at", "where_link": {"to": null}, "get": "name"}, "current_role": {"find": "worked_at", "where_link": {"to": null}, "get": "title"}}}"#;

// ===========================================================
// Shortcuts — per-shape `shortcuts:` block as JSON
// ===========================================================

pub static SHAPE_SHORTCUTS_JSON: &str = r#"{}"#;
