// DO NOT EDIT — generated from platform/ontology/shapes/order.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use super::sdk_prelude::*;

/// A purchase order. Contains products and tracks delivery.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct Order {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub all_day: Option<bool>,
    pub body: Option<String>,
    pub currency: Option<String>,
    pub current_url: Option<String>,
    pub date_updated: Option<String>,
    pub delivery_date: Option<String>,
    pub delivery_fee: Option<f64>,
    pub delivery_instructions: Option<String>,
    pub distinct_id: Option<String>,
    pub end_date: Option<String>,
    pub eta: Option<String>,
    pub fare_breakdown: Option<serde_json::Value>,
    pub head: Option<String>,
    pub ical_uid: Option<String>,
    pub interaction_type: Option<String>,
    pub item_states: Option<serde_json::Value>,
    pub latest_arrival: Option<String>,
    pub messages: Option<serde_json::Value>,
    pub order_date: Option<String>,
    pub order_id: String,
    pub order_uuid: Option<String>,
    pub original_total: Option<String>,
    pub original_total_amount: Option<f64>,
    pub progress: Option<f64>,
    pub progress_total: Option<f64>,
    pub properties: Option<serde_json::Value>,
    pub recurrence: Option<Vec<String>>,
    pub savings: Option<f64>,
    pub show_as: Option<String>,
    pub source_title: Option<String>,
    pub source_url: Option<String>,
    pub start_date: Option<String>,
    pub status: Option<String>,
    pub subtotal: Option<f64>,
    pub summary: Option<String>,
    pub taxes: Option<f64>,
    pub timeline: Option<serde_json::Value>,
    pub timezone: Option<String>,
    pub tip_amount: Option<f64>,
    pub total: Option<String>,
    pub total_amount: Option<f64>,
    pub visibility: Option<String>,
}

pub static ORDER: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "order".into(),
    plural: Some("orders".into()),
    description: Some("A purchase order. Contains products and tracks delivery.".into()),
    fields: vec![
        FieldDef::optional("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("allDay", FieldType::Boolean),
        FieldDef::optional("body", FieldType::Text),
        FieldDef::optional("currency", FieldType::String),
        FieldDef::optional("currentUrl", FieldType::String),
        FieldDef::optional("dateUpdated", FieldType::Datetime),
        FieldDef::optional("deliveryDate", FieldType::Datetime),
        FieldDef::optional("deliveryFee", FieldType::Number),
        FieldDef::optional("deliveryInstructions", FieldType::String),
        FieldDef::optional("distinctId", FieldType::String),
        FieldDef::optional("endDate", FieldType::Datetime),
        FieldDef::optional("eta", FieldType::String),
        FieldDef::optional("fareBreakdown", FieldType::Json),
        FieldDef::optional("head", FieldType::Text),
        FieldDef::optional("icalUid", FieldType::String),
        FieldDef::optional("interactionType", FieldType::String),
        FieldDef::optional("itemStates", FieldType::Json),
        FieldDef::optional("latestArrival", FieldType::Datetime),
        FieldDef::optional("messages", FieldType::Json),
        FieldDef::optional("orderDate", FieldType::Datetime),
        FieldDef::required("orderId", FieldType::String),
        FieldDef::optional("orderUuid", FieldType::String),
        FieldDef::optional("originalTotal", FieldType::String),
        FieldDef::optional("originalTotalAmount", FieldType::Number),
        FieldDef::optional("progress", FieldType::Number),
        FieldDef::optional("progressTotal", FieldType::Number),
        FieldDef::optional("properties", FieldType::Json),
        FieldDef::optional("recurrence", FieldType::StringList),
        FieldDef::optional("savings", FieldType::Number),
        FieldDef::optional("showAs", FieldType::String),
        FieldDef::optional("sourceTitle", FieldType::String),
        FieldDef::optional("sourceUrl", FieldType::Url),
        FieldDef::optional("startDate", FieldType::Datetime),
        FieldDef::optional("status", FieldType::String),
        FieldDef::optional("subtotal", FieldType::Number),
        FieldDef::optional("summary", FieldType::String),
        FieldDef::optional("taxes", FieldType::Number),
        FieldDef::optional("timeline", FieldType::Json),
        FieldDef::optional("timezone", FieldType::String),
        FieldDef::optional("tipAmount", FieldType::Number),
        FieldDef::optional("total", FieldType::String),
        FieldDef::optional("totalAmount", FieldType::Number),
        FieldDef::optional("visibility", FieldType::String),
    ],
    out: vec![
        EdgeDef { label: "at_namespace".into(), to: Some("actor".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "contains".into(), to: Some("product".into()), from: None, card: Cardinality::Many },
        EdgeDef { label: "shipped_to".into(), to: Some("place".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "purchased_at".into(), to: Some("place".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "delivered_via".into(), to: Some("trip".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "tracked_at".into(), to: Some("webpage".into()), from: None, card: Cardinality::One },
    ],
    also: vec!["event".into()],
    identity: vec!["at".into(), "orderId".into()],
    display: Some(DisplaySpec {
        subtitle: Some("total".into()),
        highlights: vec!["startDate".into(), "endDate".into(), "location".into()],
        ..DisplaySpec::default()
    }),
    ..ShapeDef::default()
});
