// DO NOT EDIT — generated from platform/ontology/shapes/payment_method.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use super::sdk_prelude::*;

/// A saved payment instrument — credit/debit card, PayPal/Venmo account,
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct PaymentMethod {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub balance: Option<f64>,
    pub bin_range: Option<String>,
    pub brand: Option<String>,
    pub currency: Option<String>,
    pub custom_description: Option<String>,
    pub display_name: Option<String>,
    pub exp_month: Option<i64>,
    pub exp_year: Option<i64>,
    pub expiration_date: Option<String>,
    pub fingerprint: Option<String>,
    pub holder_name: Option<String>,
    pub identifier: String,
    pub is_default: Option<bool>,
    pub is_expired: Option<bool>,
    pub is_primary: Option<bool>,
    pub is_selected: Option<bool>,
    pub last4: Option<String>,
    pub metadata: Option<serde_json::Value>,
    pub provider_tokens: Option<serde_json::Value>,
    pub status: Option<String>,
    pub subtype: Option<String>,
    pub type_: Option<String>,
}

pub static PAYMENT_METHOD: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "payment_method".into(),
    plural: Some("payment_methods".into()),
    description: Some("A saved payment instrument — credit/debit card, PayPal/Venmo account,".into()),
    fields: vec![
        FieldDef::optional("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("balance", FieldType::Number),
        FieldDef::optional("binRange", FieldType::String),
        FieldDef::optional("brand", FieldType::String),
        FieldDef::optional("currency", FieldType::String),
        FieldDef::optional("customDescription", FieldType::String),
        FieldDef::optional("displayName", FieldType::String),
        FieldDef::optional("expMonth", FieldType::Integer),
        FieldDef::optional("expYear", FieldType::Integer),
        FieldDef::optional("expirationDate", FieldType::String),
        FieldDef::optional("fingerprint", FieldType::String),
        FieldDef::optional("holderName", FieldType::String),
        FieldDef::required("identifier", FieldType::String),
        FieldDef::optional("isDefault", FieldType::Boolean),
        FieldDef::optional("isExpired", FieldType::Boolean),
        FieldDef::optional("isPrimary", FieldType::Boolean),
        FieldDef::optional("isSelected", FieldType::Boolean),
        FieldDef::optional("last4", FieldType::String),
        FieldDef::optional("metadata", FieldType::Json),
        FieldDef::optional("providerTokens", FieldType::Json),
        FieldDef::optional("status", FieldType::String),
        FieldDef::optional("subtype", FieldType::String),
        FieldDef::optional("type", FieldType::String),
    ],
    out: vec![
        EdgeDef { label: "at_namespace".into(), to: Some("actor".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "saved_under".into(), to: Some("account".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "held_by".into(), to: Some("person".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "billed_to".into(), to: Some("place".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "funded_by".into(), to: Some("financial_account".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "issued_by".into(), to: Some("actor".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "tied_to".into(), to: Some("membership".into()), from: None, card: Cardinality::One },
    ],
    identity: vec!["at".into(), "identifier".into()],
    display: Some(DisplaySpec {
        subtitle: Some("displayName".into()),
        ..DisplaySpec::default()
    }),
    prior_art: vec![
        PriorArtDef { source: "Stripe PaymentMethod API".into(), url: Some("https://docs.stripe.com/api/payment_methods/object".into()), notes: Some("The gold standard. Our type/subtype ≈ Stripe's `type` + `card.brand`; last4/expMonth/expYear/fingerprint map 1:1 to `card.last4/exp_month/exp_year/fingerprint`. Stripe's billing_details is our `billingAddress` relation. Stripe's `pm_xxx` id is the canonical opaque handle.".into()) },
        PriorArtDef { source: "PCI DSS v4.0 Requirement 3 (Protect Stored Account Data)".into(), url: Some("https://www.pcisecuritystandards.org/document_library/".into()), notes: Some("Defines what's storable: PAN truncated, expiry, cardholder name, service code. FORBIDS full PAN (unencrypted), CVV/CVC2/CID, PIN/PIN block, track data. This shape carries only the permitted subset. Opaque tokens are NOT card data under PCI — they're the merchant/provider's detokenization references; storing them is the recommended mitigation (Req. 3.5 tokenization).".into()) },
        PriorArtDef { source: "IATA Resolution 890 / PADIS Form-of-Payment codes".into(), url: Some("https://www.iata.org/en/publications/store/passenger-and-baggage-tariffs/".into()), notes: Some("Source for the airline 2-char `subtype` codes: AX (Amex), VI (Visa), MC (MasterCard), DS (Discover), DC (Diners), TP (UATP), JC (JCB), UP (UnionPay). These are the codes embedded in PNR FOP fields and EMD records. We keep them verbatim so airline checkout round-trips work without translation.".into()) },
        PriorArtDef { source: "W3C Payment Request API / Payment Method Identifiers".into(), url: Some("https://www.w3.org/TR/payment-method-id/".into()), notes: Some("Browser-standard payment abstraction. `basic-card`, `https://apple.com/apple-pay`, `https://google.com/pay`, `https://paypal.com` are the method identifiers — our type/subtype combo is a normalized form.".into()) },
        PriorArtDef { source: "Apple Pay Payment Token / Google Pay Network Token".into(), url: Some("https://developer.apple.com/documentation/passkit/apple_pay/payment_token_format_reference".into()), notes: Some("Device-bound token replaces the PAN on-chain. The DPAN and cryptogram live in `providerTokens`; `last4` on the wallet surfaces the DEVICE last-4, not the funding card's last-4.".into()) },
        PriorArtDef { source: "schema.org/PaymentMethod + LoyaltyProgram".into(), url: Some("https://schema.org/PaymentMethod".into()), notes: Some("schema.org's PaymentMethod is a thin enum (CreditCard, Cash, PaymentCard, ByInvoice). We extend it into a real shape with tokens and holder. Our `type` overlaps its enumeration values.".into()) },
        PriorArtDef { source: "PayPal Billing Agreements / Vault".into(), url: Some("https://developer.paypal.com/docs/multiparty/vault/".into()), notes: Some("PayPal's saved-method pattern — billingAgreementId is the opaque handle, used like our `providerTokens`. Payer given_name → `holderName`. No last4 (PayPal-as-wallet has no card number surface); our shape accommodates via nullable last4.".into()) },
        PriorArtDef { source: "EMVCo Tokenisation Framework v2.0".into(), url: Some("https://www.emvco.com/specifications/payment-tokenisation/".into()), notes: Some("Industry spec for network tokens (Visa Token Service, Mastercard MDES). Defines token requestor, token reference id, PAR (Payment Account Reference) — PAR is the cross-token dedupe primitive our `fingerprint` field aligns with when the provider surfaces it.".into()) },
    ],
    ..ShapeDef::default()
});
