// DO NOT EDIT — generated from platform/ontology/shapes/place.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use super::sdk_prelude::*;

/// A physical location — address, building, city, or point of interest.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct Place {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub accuracy: Option<String>,
    pub business_status: Option<String>,
    pub categories: Option<Vec<String>>,
    pub city: Option<String>,
    pub closed_message: Option<String>,
    pub country: Option<String>,
    pub country_code: Option<String>,
    pub district: Option<String>,
    pub eta: Option<String>,
    pub feature_type: Option<String>,
    pub full_address: Option<String>,
    pub google_place_id: Option<String>,
    pub hours: Option<serde_json::Value>,
    pub is_orderable: Option<bool>,
    pub latitude: Option<f64>,
    pub locality: Option<String>,
    pub longitude: Option<f64>,
    pub mapbox_id: Option<String>,
    pub neighborhood: Option<String>,
    pub phone: Option<String>,
    pub place_formatted: Option<String>,
    pub postal_code: Option<String>,
    pub price_level: Option<String>,
    pub product_count: Option<i64>,
    pub rating: Option<f64>,
    pub region: Option<String>,
    pub review_count: Option<i64>,
    pub street: Option<String>,
    pub street_number: Option<String>,
    pub timezone: Option<String>,
    pub website: Option<String>,
    pub wikidata_id: Option<String>,
}

pub static PLACE: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "place".into(),
    plural: Some("places".into()),
    description: Some("A physical location — address, building, city, or point of interest.".into()),
    fields: vec![
        FieldDef::optional("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("accuracy", FieldType::String),
        FieldDef::optional("businessStatus", FieldType::String),
        FieldDef::optional("categories", FieldType::StringList),
        FieldDef::optional("city", FieldType::String),
        FieldDef::optional("closedMessage", FieldType::String),
        FieldDef::optional("country", FieldType::String),
        FieldDef::optional("countryCode", FieldType::String),
        FieldDef::optional("district", FieldType::String),
        FieldDef::optional("eta", FieldType::String),
        FieldDef::optional("featureType", FieldType::String),
        FieldDef::optional("fullAddress", FieldType::String),
        FieldDef::optional("googlePlaceId", FieldType::String),
        FieldDef::optional("hours", FieldType::Json),
        FieldDef::optional("isOrderable", FieldType::Boolean),
        FieldDef::optional("latitude", FieldType::Number),
        FieldDef::optional("locality", FieldType::String),
        FieldDef::optional("longitude", FieldType::Number),
        FieldDef::optional("mapboxId", FieldType::String),
        FieldDef::optional("neighborhood", FieldType::String),
        FieldDef::optional("phone", FieldType::String),
        FieldDef::optional("placeFormatted", FieldType::String),
        FieldDef::optional("postalCode", FieldType::String),
        FieldDef::optional("priceLevel", FieldType::String),
        FieldDef::optional("productCount", FieldType::Integer),
        FieldDef::optional("rating", FieldType::Number),
        FieldDef::optional("region", FieldType::String),
        FieldDef::optional("reviewCount", FieldType::Integer),
        FieldDef::optional("street", FieldType::String),
        FieldDef::optional("streetNumber", FieldType::String),
        FieldDef::optional("timezone", FieldType::String),
        FieldDef::optional("website", FieldType::Url),
        FieldDef::optional("wikidataId", FieldType::String),
    ],
    identity_any: vec!["googlePlaceId".into(), "mapboxId".into()],
    display: Some(DisplaySpec {
        subtitle: Some("featureType".into()),
        image: Some("image".into()),
        body: Some("fullAddress".into()),
        highlights: vec!["city".into(), "country".into(), "rating".into()],
        ..DisplaySpec::default()
    }),
    ..ShapeDef::default()
});
