// DO NOT EDIT — generated from platform/ontology/shapes/platform.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use super::sdk_prelude::*;

/// An identity namespace and how to present it — the registry a person's
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct Platform {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub aisle: Option<String>,
    pub availability: Option<String>,
    pub barcode: Option<String>,
    pub calories: Option<f64>,
    pub categories: Option<Vec<String>>,
    pub category: Option<String>,
    pub currency: Option<String>,
    pub customization_groups: Option<serde_json::Value>,
    pub department: Option<String>,
    pub federated: Option<bool>,
    pub images: Option<serde_json::Value>,
    pub nova_group: Option<i64>,
    pub nutrition_score: Option<String>,
    pub original_price: Option<String>,
    pub original_price_amount: Option<f64>,
    pub price: Option<String>,
    pub price_amount: Option<f64>,
    pub protocol: Option<String>,
    pub quantity: Option<i64>,
    pub serving_size: Option<String>,
    pub sku: Option<String>,
    pub slug: String,
    pub sold_by_weight: Option<bool>,
    pub url_template: Option<String>,
    pub weight: Option<String>,
    pub weight_unit: Option<String>,
    pub weight_value: Option<f64>,
}

pub static PLATFORM: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "platform".into(),
    plural: Some("platforms".into()),
    description: Some("An identity namespace and how to present it — the registry a person's".into()),
    fields: vec![
        FieldDef::optional("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("aisle", FieldType::String),
        FieldDef::optional("availability", FieldType::String),
        FieldDef::optional("barcode", FieldType::String),
        FieldDef::optional("calories", FieldType::Number),
        FieldDef::optional("categories", FieldType::StringList),
        FieldDef::optional("category", FieldType::String),
        FieldDef::optional("currency", FieldType::String),
        FieldDef::optional("customizationGroups", FieldType::Json),
        FieldDef::optional("department", FieldType::String),
        FieldDef::optional("federated", FieldType::Boolean),
        FieldDef::optional("images", FieldType::Json),
        FieldDef::optional("novaGroup", FieldType::Integer),
        FieldDef::optional("nutritionScore", FieldType::String),
        FieldDef::optional("originalPrice", FieldType::String),
        FieldDef::optional("originalPriceAmount", FieldType::Number),
        FieldDef::optional("price", FieldType::String),
        FieldDef::optional("priceAmount", FieldType::Number),
        FieldDef::optional("protocol", FieldType::String),
        FieldDef::optional("quantity", FieldType::Integer),
        FieldDef::optional("servingSize", FieldType::String),
        FieldDef::optional("sku", FieldType::String),
        FieldDef::required("slug", FieldType::String),
        FieldDef::optional("soldByWeight", FieldType::Boolean),
        FieldDef::optional("urlTemplate", FieldType::String),
        FieldDef::optional("weight", FieldType::String),
        FieldDef::optional("weightUnit", FieldType::String),
        FieldDef::optional("weightValue", FieldType::Number),
    ],
    also: vec!["product".into()],
    identity: vec!["slug".into()],
    display: Some(DisplaySpec {
        subtitle: Some("category".into()),
        ..DisplaySpec::default()
    }),
    groups: vec![
        FieldGroupDef { name: "Identity".into(), fields: vec!["slug".into(), "category".into()] },
        FieldGroupDef { name: "Federation".into(), fields: vec!["federated".into(), "protocol".into()] },
        FieldGroupDef { name: "Presentation".into(), fields: vec!["urlTemplate".into()] },
    ],
    prior_art: vec![
        PriorArtDef { source: "schema.org/SoftwareApplication".into(), url: Some("https://schema.org/SoftwareApplication".into()), notes: Some("A platform is a product (we extend it) — most platforms are software. We stop at `also: [product]` rather than `[software]` because email and phone are protocol namespaces, not software; product is the broadest correct base, and `category` already carries social/messaging/etc.".into()) },
        PriorArtDef { source: "ActivityPub / WebFinger (acct: URI)".into(), url: Some("https://www.w3.org/TR/activitypub/".into()), notes: Some("`federated` + `instance` (on the identity entry) + `protocol` model the federated case: a handle is scoped by its homeserver, the canonical id stays the actor URI. WebFinger's user@host split maps to handle@instance.".into()) },
        PriorArtDef { source: "schema.org ContactPoint".into(), url: Some("https://schema.org/ContactPoint".into()), notes: Some("`category: contact` (email, phone) aligns with ContactPoint as a reach key rather than a hosted account.".into()) },
    ],
    ..ShapeDef::default()
});
