// DO NOT EDIT — generated from platform/ontology/shapes/reservation.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use super::sdk_prelude::*;

/// A forward commitment to a future thing — a flight booking, a hotel
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct Reservation {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub all_day: Option<bool>,
    pub available_actions: Option<Vec<String>>,
    pub base_amount: Option<f64>,
    pub booking_time: Option<String>,
    pub booking_type: Option<String>,
    pub checkin_url: Option<String>,
    pub conditions: Option<serde_json::Value>,
    pub currency: Option<String>,
    pub current_url: Option<String>,
    pub date_updated: Option<String>,
    pub distinct_id: Option<String>,
    pub end_date: Option<String>,
    pub end_time: Option<String>,
    pub ical_uid: Option<String>,
    pub modified_time: Option<String>,
    pub party_size: Option<i64>,
    pub properties: Option<serde_json::Value>,
    pub recurrence: Option<Vec<String>>,
    pub reservation_id: String,
    pub reservation_type: Option<String>,
    pub show_as: Option<String>,
    pub source_title: Option<String>,
    pub source_url: Option<String>,
    pub start_date: Option<String>,
    pub start_time: Option<String>,
    pub status: Option<String>,
    pub tax_amount: Option<f64>,
    pub timezone: Option<String>,
    pub total_amount: Option<f64>,
    pub visibility: Option<String>,
    pub void_window_ends_at: Option<String>,
}

pub static RESERVATION: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "reservation".into(),
    plural: Some("reservations".into()),
    description: Some("A forward commitment to a future thing — a flight booking, a hotel".into()),
    fields: vec![
        FieldDef::optional("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("allDay", FieldType::Boolean),
        FieldDef::optional("availableActions", FieldType::StringList),
        FieldDef::optional("baseAmount", FieldType::Number),
        FieldDef::optional("bookingTime", FieldType::Datetime),
        FieldDef::optional("bookingType", FieldType::String),
        FieldDef::optional("checkinUrl", FieldType::Url),
        FieldDef::optional("conditions", FieldType::Json),
        FieldDef::optional("currency", FieldType::String),
        FieldDef::optional("currentUrl", FieldType::String),
        FieldDef::optional("dateUpdated", FieldType::Datetime),
        FieldDef::optional("distinctId", FieldType::String),
        FieldDef::optional("endDate", FieldType::Datetime),
        FieldDef::optional("endTime", FieldType::Datetime),
        FieldDef::optional("icalUid", FieldType::String),
        FieldDef::optional("modifiedTime", FieldType::Datetime),
        FieldDef::optional("partySize", FieldType::Integer),
        FieldDef::optional("properties", FieldType::Json),
        FieldDef::optional("recurrence", FieldType::StringList),
        FieldDef::required("reservationId", FieldType::String),
        FieldDef::optional("reservationType", FieldType::String),
        FieldDef::optional("showAs", FieldType::String),
        FieldDef::optional("sourceTitle", FieldType::String),
        FieldDef::optional("sourceUrl", FieldType::Url),
        FieldDef::optional("startDate", FieldType::Datetime),
        FieldDef::optional("startTime", FieldType::Datetime),
        FieldDef::optional("status", FieldType::String),
        FieldDef::optional("taxAmount", FieldType::Number),
        FieldDef::optional("timezone", FieldType::String),
        FieldDef::optional("totalAmount", FieldType::Number),
        FieldDef::optional("visibility", FieldType::String),
        FieldDef::optional("voidWindowEndsAt", FieldType::Datetime),
    ],
    out: vec![
        EdgeDef { label: "at_namespace".into(), to: Some("actor".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "covers_trip".into(), to: Some("trip".into()), from: None, card: Cardinality::Many },
        EdgeDef { label: "held_at".into(), to: Some("place".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "for".into(), to: Some("event".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "accommodates".into(), to: Some("person".into()), from: None, card: Cardinality::Many },
        EdgeDef { label: "booked_for".into(), to: Some("person".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "booked_under".into(), to: Some("account".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "brokered_by".into(), to: Some("actor".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "enrolled_in".into(), to: Some("membership".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "placed_via".into(), to: Some("order".into()), from: None, card: Cardinality::One },
        EdgeDef { label: "issued_pass".into(), to: Some("pass".into()), from: None, card: Cardinality::Many },
        EdgeDef { label: "derived_from".into(), to: Some("offer".into()), from: None, card: Cardinality::One },
    ],
    also: vec!["event".into()],
    identity: vec!["at".into(), "reservationId".into()],
    display: Some(DisplaySpec {
        subtitle: Some("reservationType".into()),
        highlights: vec!["startDate".into(), "endDate".into(), "location".into()],
        ..DisplaySpec::default()
    }),
    ..ShapeDef::default()
});
