// DO NOT EDIT — generated from platform/ontology/shapes/reservation.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use super::sdk_prelude::*;

/// A forward commitment to a future thing — a flight booking, a hotel
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct Reservation {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub all_day: Option<bool>,
    pub available_actions: Option<Vec<String>>,
    pub base_amount: Option<f64>,
    pub booking_time: Option<String>,
    pub booking_type: Option<String>,
    pub checkin_url: Option<String>,
    pub conditions: Option<serde_json::Value>,
    pub currency: Option<String>,
    pub current_url: Option<String>,
    pub date_updated: Option<String>,
    pub distinct_id: Option<String>,
    pub end_date: Option<String>,
    pub end_time: Option<String>,
    pub ical_uid: Option<String>,
    pub modified_time: Option<String>,
    pub party_size: Option<i64>,
    pub properties: Option<serde_json::Value>,
    pub recurrence: Option<Vec<String>>,
    pub reservation_id: String,
    pub reservation_type: Option<String>,
    pub show_as: Option<String>,
    pub source_title: Option<String>,
    pub source_url: Option<String>,
    pub start_date: Option<String>,
    pub start_time: Option<String>,
    pub status: Option<String>,
    pub tax_amount: Option<f64>,
    pub timezone: Option<String>,
    pub total_amount: Option<f64>,
    pub visibility: Option<String>,
    pub void_window_ends_at: Option<String>,
}

pub static RESERVATION: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "reservation".into(),
    plural: Some("reservations".into()),
    description: Some("A forward commitment to a future thing — a flight booking, a hotel".into()),
    fields: vec![
        FieldDef::optional("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("allDay", FieldType::Boolean),
        FieldDef::optional("availableActions", FieldType::StringList),
        FieldDef::optional("baseAmount", FieldType::Number),
        FieldDef::optional("bookingTime", FieldType::Datetime),
        FieldDef::optional("bookingType", FieldType::String),
        FieldDef::optional("checkinUrl", FieldType::Url),
        FieldDef::optional("conditions", FieldType::Json),
        FieldDef::optional("currency", FieldType::String),
        FieldDef::optional("currentUrl", FieldType::String),
        FieldDef::optional("dateUpdated", FieldType::Datetime),
        FieldDef::optional("distinctId", FieldType::String),
        FieldDef::optional("endDate", FieldType::Datetime),
        FieldDef::optional("endTime", FieldType::Datetime),
        FieldDef::optional("icalUid", FieldType::String),
        FieldDef::optional("modifiedTime", FieldType::Datetime),
        FieldDef::optional("partySize", FieldType::Integer),
        FieldDef::optional("properties", FieldType::Json),
        FieldDef::optional("recurrence", FieldType::StringList),
        FieldDef::required("reservationId", FieldType::String),
        FieldDef::optional("reservationType", FieldType::String),
        FieldDef::optional("showAs", FieldType::String),
        FieldDef::optional("sourceTitle", FieldType::String),
        FieldDef::optional("sourceUrl", FieldType::Url),
        FieldDef::optional("startDate", FieldType::Datetime),
        FieldDef::optional("startTime", FieldType::Datetime),
        FieldDef::optional("status", FieldType::String),
        FieldDef::optional("taxAmount", FieldType::Number),
        FieldDef::optional("timezone", FieldType::String),
        FieldDef::optional("totalAmount", FieldType::Number),
        FieldDef::optional("visibility", FieldType::String),
        FieldDef::optional("voidWindowEndsAt", FieldType::Datetime),
    ],
    also: vec!["event".into()],
    identity: vec!["at".into(), "reservationId".into()],
    display: Some(DisplaySpec {
        subtitle: Some("reservationType".into()),
        highlights: vec!["startDate".into(), "endDate".into(), "location".into()],
        ..DisplaySpec::default()
    }),
    prior_art: vec![
        PriorArtDef { source: "schema.org/Reservation".into(), url: Some("https://schema.org/Reservation".into()), notes: Some("Base vocabulary: reservationFor, reservationId, reservationStatus, reservedTicket, underName, bookingTime, modifiedTime, totalPrice, priceCurrency. We fold FlightReservation / LodgingReservation / FoodEstablishmentReservation into a single shape with a reservationType discriminator (AgentOS convention — see `trip.tripType`, `event.eventType`). Flight-specific fields (boardingGroup, seat) live on pass, not here.".into()) },
        PriorArtDef { source: "schema.org/ReservationStatusType".into(), url: Some("https://schema.org/ReservationStatusType".into()), notes: Some("Extended beyond schema.org's ConfirmedCancelledHoldPending set to add `no_show` and `completed` — values that matter for post-hoc reasoning but schema.org lacks.".into()) },
        PriorArtDef { source: "Duffel Orders API".into(), url: Some("https://duffel.com/docs/api/v2/orders".into()), notes: Some("Canonical flight-booking top-level entity. Our `reservationId` = booking_reference; `availableActions` = available_actions; `voidWindowEndsAt` = void_window_ends_at; `conditions` = conditions (change_before_departure, refund_before_departure). Duffel names the entity `Order`; we chose `reservation` to free up `order` for pure-commerce semantics.".into()) },
        PriorArtDef { source: "IATA NDC OrderViewRS".into(), url: Some("https://www.iata.org/en/programs/airline-distribution/retailing/ndc/".into()), notes: Some("NDC normalizes passengers to a top-level PaxList referenced by ID. Our graph gets the same effect with `passengers: person[]` — people are first-class nodes and the same `person` can appear on many reservations. Services (seat, baggage, meal) live on `pass`.".into()) },
        PriorArtDef { source: "ActivityStreams 2.0 (Invite / Accept / Leave / Reject)".into(), url: Some("https://www.w3.org/TR/activitystreams-vocabulary/".into()), notes: Some("Commitment lifecycle is an append-only stream of activities (booked, held, checked_in, rebooked, cancelled) rather than a single lossy enum. We use `status` for the snapshot and rely on back-links from `activity` nodes for the history — the same pattern FEP-8a8e recommends for ActivityPub event-side state.".into()) },
        PriorArtDef { source: "FEP-8a8e Event interop".into(), url: Some("https://w3id.org/fep/8a8e".into()), notes: Some("Splits supply-side status (on the event/flight) from demand-side status (on the attendee/passenger). We mirror this by keeping `status` on reservation (passenger-side) separate from any cancellation/delay state on the `flight` or `trip` itself.".into()) },
        PriorArtDef { source: "Valueflows / REA — Commitment".into(), url: Some("https://www.valueflo.ws/concepts/flows/".into()), notes: Some("REA accounting framing: a reservation IS a commitment with provider, receiver, resourceConformsTo, quantity, and time window. Useful lens for future extension (hotel nights, car rental days).".into()) },
    ],
    ..ShapeDef::default()
});
