// DO NOT EDIT — generated from platform/ontology/shapes/spec.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use agentos_graph::{
    Cardinality, DerivedBinding, DisplaySpec, EdgeDef, FieldDef, FieldType,
    ShapeDef, ShortcutDef,
};
use once_cell::sync::Lazy;
use serde::{Deserialize, Serialize};

/// A spec — a design document describing work to be done.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct Spec {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub all_day: Option<bool>,
    pub current_url: Option<String>,
    pub date_updated: Option<String>,
    pub distinct_id: Option<String>,
    pub encoding: Option<String>,
    pub end_date: Option<String>,
    pub filename: Option<String>,
    pub format: Option<String>,
    pub ical_uid: Option<String>,
    pub kind: Option<String>,
    pub labels: Option<Vec<String>>,
    pub line_count: Option<i64>,
    pub mime_type: Option<String>,
    pub parent_id: Option<String>,
    pub path: Option<String>,
    pub priority: Option<i64>,
    pub problem: Option<String>,
    pub project_id: Option<String>,
    pub properties: Option<serde_json::Value>,
    pub recurrence: Option<Vec<String>>,
    pub remote_id: Option<String>,
    pub sha: Option<String>,
    pub show_as: Option<String>,
    pub size: Option<i64>,
    pub source_title: Option<String>,
    pub source_url: Option<String>,
    pub start_date: Option<String>,
    pub state: Option<String>,
    pub status: Option<String>,
    pub success_criteria: Option<String>,
    pub target: Option<serde_json::Value>,
    pub target_date: Option<String>,
    pub timezone: Option<String>,
    pub visibility: Option<String>,
}

pub static SPEC: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "spec".into(),
    plural: Some("specs".into()),
    description: Some("A spec — a design document describing work to be done.".into()),
    fields: vec![
        FieldDef::optional("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("allDay", FieldType::Boolean),
        FieldDef::optional("currentUrl", FieldType::String),
        FieldDef::optional("dateUpdated", FieldType::Datetime),
        FieldDef::optional("distinctId", FieldType::String),
        FieldDef::optional("encoding", FieldType::String),
        FieldDef::optional("endDate", FieldType::Datetime),
        FieldDef::optional("filename", FieldType::String),
        FieldDef::optional("format", FieldType::String),
        FieldDef::optional("icalUid", FieldType::String),
        FieldDef::optional("kind", FieldType::String),
        FieldDef::optional("labels", FieldType::StringList),
        FieldDef::optional("lineCount", FieldType::Integer),
        FieldDef::optional("mimeType", FieldType::String),
        FieldDef::optional("parentId", FieldType::String),
        FieldDef::optional("path", FieldType::String),
        FieldDef::optional("priority", FieldType::Integer),
        FieldDef::optional("problem", FieldType::Text),
        FieldDef::optional("projectId", FieldType::String),
        FieldDef::optional("properties", FieldType::Json),
        FieldDef::optional("recurrence", FieldType::StringList),
        FieldDef::optional("remoteId", FieldType::String),
        FieldDef::optional("sha", FieldType::String),
        FieldDef::optional("showAs", FieldType::String),
        FieldDef::optional("size", FieldType::Integer),
        FieldDef::optional("sourceTitle", FieldType::String),
        FieldDef::optional("sourceUrl", FieldType::Url),
        FieldDef::optional("startDate", FieldType::Datetime),
        FieldDef::optional("state", FieldType::String),
        FieldDef::optional("status", FieldType::String),
        FieldDef::optional("successCriteria", FieldType::Text),
        FieldDef::optional("target", FieldType::Json),
        FieldDef::optional("targetDate", FieldType::Datetime),
        FieldDef::optional("timezone", FieldType::String),
        FieldDef::optional("visibility", FieldType::String),
    ],
    also: vec!["task".into(), "file".into()],
    display: Some(DisplaySpec {
        subtitle: Some("state".into()),
        highlights: vec!["startDate".into(), "endDate".into(), "location".into()],
        ..DisplaySpec::default()
    }),
    ..ShapeDef::default()
});
