// DO NOT EDIT — generated from platform/ontology/shapes/transition.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use super::sdk_prelude::*;

/// An identity change — name, gender, religion, sports team, anything
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct Transition {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub additional_name: Option<String>,
    pub all_day: Option<bool>,
    pub current_url: Option<String>,
    pub date_updated: Option<String>,
    pub distinct_id: Option<String>,
    pub end_date: Option<String>,
    pub family_name: Option<String>,
    pub gender: Option<String>,
    pub given_name: Option<String>,
    pub honorific_prefix: Option<String>,
    pub honorific_suffix: Option<String>,
    pub ical_uid: Option<String>,
    pub legal_name: Option<String>,
    pub maiden_name: Option<String>,
    pub name_order: Option<String>,
    pub nickname: Option<String>,
    pub phonetic_family_name: Option<String>,
    pub phonetic_given_name: Option<String>,
    pub properties: Option<serde_json::Value>,
    pub recurrence: Option<Vec<String>>,
    pub show_as: Option<String>,
    pub sort_as: Option<String>,
    pub source_title: Option<String>,
    pub source_url: Option<String>,
    pub start_date: Option<String>,
    pub status: Option<String>,
    pub timezone: Option<String>,
    pub visibility: Option<String>,
}

pub static TRANSITION: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "transition".into(),
    plural: Some("transitions".into()),
    description: Some("An identity change — name, gender, religion, sports team, anything".into()),
    fields: vec![
        FieldDef::optional("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("additionalName", FieldType::String),
        FieldDef::optional("allDay", FieldType::Boolean),
        FieldDef::optional("currentUrl", FieldType::String),
        FieldDef::optional("dateUpdated", FieldType::Datetime),
        FieldDef::optional("distinctId", FieldType::String),
        FieldDef::optional("endDate", FieldType::Datetime),
        FieldDef::optional("familyName", FieldType::String),
        FieldDef::optional("gender", FieldType::String),
        FieldDef::optional("givenName", FieldType::String),
        FieldDef::optional("honorificPrefix", FieldType::String),
        FieldDef::optional("honorificSuffix", FieldType::String),
        FieldDef::optional("icalUid", FieldType::String),
        FieldDef::optional("legalName", FieldType::String),
        FieldDef::optional("maidenName", FieldType::String),
        FieldDef::optional("nameOrder", FieldType::String),
        FieldDef::optional("nickname", FieldType::String),
        FieldDef::optional("phoneticFamilyName", FieldType::String),
        FieldDef::optional("phoneticGivenName", FieldType::String),
        FieldDef::optional("properties", FieldType::Json),
        FieldDef::optional("recurrence", FieldType::StringList),
        FieldDef::optional("showAs", FieldType::String),
        FieldDef::optional("sortAs", FieldType::String),
        FieldDef::optional("sourceTitle", FieldType::String),
        FieldDef::optional("sourceUrl", FieldType::Url),
        FieldDef::optional("startDate", FieldType::Datetime),
        FieldDef::optional("status", FieldType::String),
        FieldDef::optional("timezone", FieldType::String),
        FieldDef::optional("visibility", FieldType::String),
    ],
    also: vec!["event".into()],
    display: Some(DisplaySpec {
        subtitle: Some("startDate".into()),
        highlights: vec!["startDate".into(), "givenName".into(), "familyName".into(), "gender".into()],
        ..DisplaySpec::default()
    }),
    prior_art: vec![
        PriorArtDef { source: "Event Sourcing (Fowler)".into(), url: Some("https://martinfowler.com/eaaDev/EventSourcing.html".into()), notes: Some("Past-tense events as facts; entity state = fold over the event stream. `transition` is the past-tense event-node; the `latest:` resolver is the fold. Reuses canonical field names — no `new_*` prefix per the event-sourcing convention.".into()) },
        PriorArtDef { source: "Palantir Foundry — Action Log Objects".into(), url: Some("https://www.palantir.com/docs/foundry/announcements/2022-10/index.html".into()), notes: Some("Palantir reifies every mutation as a queryable Action Log Object — same shape as our reified `transition` event. They type Actions per-mutation (`AssignEmployee` etc.); we collapse to one umbrella shape with optional fields for agent-OS ergonomics (operations not known in advance).".into()) },
        PriorArtDef { source: "IMO / GISIS maritime registry — particulars change".into(), url: Some("https://gisis.imo.org/public/default.aspx".into()), notes: Some("50-year-old domain proves the pattern: stable identifier (IMO number) + canonical property names + reified change events (name/flag/owner change). `Person.id` ↔ `Ship.imo`; `transition.gender` ↔ a `flag_change` on a ship.".into()) },
        PriorArtDef { source: "FHIR R5 HumanName.use + HumanName.period".into(), url: Some("https://hl7.org/fhir/datatypes.html#HumanName".into()), notes: Some("FHIR encodes dated names via multi-value on the Patient (no event-node). We lift the same pattern to an event-node because the change has its own date + place + authority context worth capturing as a first-class graph entity.".into()) },
        PriorArtDef { source: "Wikidata P735/P734/P21 + P580/P582 qualifiers".into(), url: Some("https://www.wikidata.org/wiki/Property:P735".into()), notes: Some("Property statements with start-time/end-time qualifiers. Validates \"reuse canonical field name + date positions in time\".".into()) },
    ],
    ..ShapeDef::default()
});
