// DO NOT EDIT — generated from platform/ontology/shapes/transaction.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use super::sdk_prelude::*;

/// A financial transaction — credit card charge, bank transfer, etc.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct Transaction {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub all_day: Option<bool>,
    pub amount: Option<f64>,
    pub balance: Option<f64>,
    pub category: Option<String>,
    pub currency: Option<String>,
    pub current_url: Option<String>,
    pub date_updated: Option<String>,
    pub details: Option<serde_json::Value>,
    pub distinct_id: Option<String>,
    pub end_date: Option<String>,
    pub ical_uid: Option<String>,
    pub notes: Option<String>,
    pub pending: Option<bool>,
    pub posting_date: Option<String>,
    pub properties: Option<serde_json::Value>,
    pub recurrence: Option<Vec<String>>,
    pub recurring: Option<bool>,
    pub show_as: Option<String>,
    pub source_title: Option<String>,
    pub source_url: Option<String>,
    pub start_date: Option<String>,
    pub status: Option<String>,
    pub timezone: Option<String>,
    pub type_: Option<String>,
    pub visibility: Option<String>,
}

pub static TRANSACTION: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "transaction".into(),
    plural: Some("transactions".into()),
    description: Some("A financial transaction — credit card charge, bank transfer, etc.".into()),
    fields: vec![
        FieldDef::required("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("allDay", FieldType::Boolean),
        FieldDef::optional("amount", FieldType::Number),
        FieldDef::optional("balance", FieldType::Number),
        FieldDef::optional("category", FieldType::String),
        FieldDef::optional("currency", FieldType::String),
        FieldDef::optional("currentUrl", FieldType::String),
        FieldDef::optional("dateUpdated", FieldType::Datetime),
        FieldDef::optional("details", FieldType::Json),
        FieldDef::optional("distinctId", FieldType::String),
        FieldDef::optional("endDate", FieldType::Datetime),
        FieldDef::optional("icalUid", FieldType::String),
        FieldDef::optional("notes", FieldType::String),
        FieldDef::optional("pending", FieldType::Boolean),
        FieldDef::optional("postingDate", FieldType::Datetime),
        FieldDef::optional("properties", FieldType::Json),
        FieldDef::optional("recurrence", FieldType::StringList),
        FieldDef::optional("recurring", FieldType::Boolean),
        FieldDef::optional("showAs", FieldType::String),
        FieldDef::optional("sourceTitle", FieldType::String),
        FieldDef::optional("sourceUrl", FieldType::Url),
        FieldDef::optional("startDate", FieldType::Datetime),
        FieldDef::optional("status", FieldType::String),
        FieldDef::optional("timezone", FieldType::String),
        FieldDef::optional("type", FieldType::String),
        FieldDef::optional("visibility", FieldType::String),
    ],
    also: vec!["event".into()],
    identity: vec!["at".into(), "id".into()],
    display: Some(DisplaySpec {
        subtitle: Some("category".into()),
        body: Some("notes".into()),
        highlights: vec!["amount".into(), "postingDate".into(), "currency".into()],
        ..DisplaySpec::default()
    }),
    prior_art: vec![
        PriorArtDef { source: "OFX (Open Financial Exchange) STMTTRN".into(), url: Some("https://financialdataexchange.org/ofx".into()), notes: Some("Direct source. Our amount/type/postingDate/balance map to STMTTRN TRNAMT/TRNTYPE/DTPOSTED/BALAMT.".into()) },
        PriorArtDef { source: "ISO 20022 payments messaging".into(), url: Some("https://www.iso20022.org/".into()), notes: Some("Modern bank-messaging. Our currency = Ccy; category ≈ purpose code; details ≈ RemittanceInformation.".into()) },
        PriorArtDef { source: "Plaid Transactions API".into(), url: Some("https://plaid.com/docs/api/products/transactions/".into()), notes: Some("Practical mirror. Our category/pending/recurring/notes match Plaid's category/pending/personal_finance_category/name fields.".into()) },
    ],
    ..ShapeDef::default()
});
