// DO NOT EDIT — generated from platform/ontology/shapes/trip.yaml.
// Regen: `python3 platform/codegen/generate.py`.

use super::sdk_prelude::*;

/// A directed journey from origin to destination — one direction of travel.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(rename_all = "camelCase", default)]
pub struct Trip {
    pub name: String,
    pub text: Option<String>,
    pub url: Option<String>,
    pub image: Option<String>,
    pub author: Option<String>,
    pub date_published: Option<String>,
    pub content: Option<String>,
    pub all_day: Option<bool>,
    pub arrival_time: Option<String>,
    pub booking_token: Option<String>,
    pub cabin_class: Option<String>,
    pub carbon_emissions: Option<serde_json::Value>,
    pub currency: Option<String>,
    pub current_url: Option<String>,
    pub date_updated: Option<String>,
    pub departure_time: Option<String>,
    pub distance: Option<String>,
    pub distinct_id: Option<String>,
    pub duration: Option<String>,
    pub duration_minutes: Option<i64>,
    pub end_date: Option<String>,
    pub fare: Option<String>,
    pub fare_amount: Option<f64>,
    pub guest: Option<serde_json::Value>,
    pub ical_uid: Option<String>,
    pub is_pool: Option<bool>,
    pub is_reserve: Option<bool>,
    pub is_scheduled: Option<bool>,
    pub is_surge: Option<bool>,
    pub marketplace: Option<String>,
    pub properties: Option<serde_json::Value>,
    pub rating: Option<String>,
    pub recurrence: Option<Vec<String>>,
    pub show_as: Option<String>,
    pub source_title: Option<String>,
    pub source_url: Option<String>,
    pub start_date: Option<String>,
    pub status: Option<String>,
    pub stops: Option<i64>,
    pub timezone: Option<String>,
    pub tracking_url: Option<String>,
    pub trip_type: Option<String>,
    pub vehicle: Option<serde_json::Value>,
    pub vehicle_type: Option<String>,
    pub visibility: Option<String>,
}

pub static TRIP: Lazy<ShapeDef> = Lazy::new(|| ShapeDef {
    name: "trip".into(),
    plural: Some("trips".into()),
    description: Some("A directed journey from origin to destination — one direction of travel.".into()),
    fields: vec![
        FieldDef::required("id", FieldType::String),
        FieldDef::required("name", FieldType::String),
        FieldDef::optional("text", FieldType::String),
        FieldDef::optional("url", FieldType::String),
        FieldDef::optional("image", FieldType::String),
        FieldDef::optional("author", FieldType::String),
        FieldDef::optional("datePublished", FieldType::String),
        FieldDef::optional("content", FieldType::String),
        FieldDef::optional("allDay", FieldType::Boolean),
        FieldDef::optional("arrivalTime", FieldType::Datetime),
        FieldDef::optional("bookingToken", FieldType::String),
        FieldDef::optional("cabinClass", FieldType::String),
        FieldDef::optional("carbonEmissions", FieldType::Json),
        FieldDef::optional("currency", FieldType::String),
        FieldDef::optional("currentUrl", FieldType::String),
        FieldDef::optional("dateUpdated", FieldType::Datetime),
        FieldDef::optional("departureTime", FieldType::Datetime),
        FieldDef::optional("distance", FieldType::String),
        FieldDef::optional("distinctId", FieldType::String),
        FieldDef::optional("duration", FieldType::String),
        FieldDef::optional("durationMinutes", FieldType::Integer),
        FieldDef::optional("endDate", FieldType::Datetime),
        FieldDef::optional("fare", FieldType::String),
        FieldDef::optional("fareAmount", FieldType::Number),
        FieldDef::optional("guest", FieldType::Json),
        FieldDef::optional("icalUid", FieldType::String),
        FieldDef::optional("isPool", FieldType::Boolean),
        FieldDef::optional("isReserve", FieldType::Boolean),
        FieldDef::optional("isScheduled", FieldType::Boolean),
        FieldDef::optional("isSurge", FieldType::Boolean),
        FieldDef::optional("marketplace", FieldType::String),
        FieldDef::optional("properties", FieldType::Json),
        FieldDef::optional("rating", FieldType::String),
        FieldDef::optional("recurrence", FieldType::StringList),
        FieldDef::optional("showAs", FieldType::String),
        FieldDef::optional("sourceTitle", FieldType::String),
        FieldDef::optional("sourceUrl", FieldType::Url),
        FieldDef::optional("startDate", FieldType::Datetime),
        FieldDef::optional("status", FieldType::String),
        FieldDef::optional("stops", FieldType::Integer),
        FieldDef::optional("timezone", FieldType::String),
        FieldDef::optional("trackingUrl", FieldType::Url),
        FieldDef::optional("tripType", FieldType::String),
        FieldDef::optional("vehicle", FieldType::Json),
        FieldDef::optional("vehicleType", FieldType::String),
        FieldDef::optional("visibility", FieldType::String),
    ],
    also: vec!["event".into()],
    identity: vec!["at".into(), "id".into()],
    display: Some(DisplaySpec {
        subtitle: Some("tripType".into()),
        highlights: vec!["startDate".into(), "endDate".into(), "location".into()],
        ..DisplaySpec::default()
    }),
    ..ShapeDef::default()
});
